### ISSUE TITLE
More WeBWorK errors

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#118]
@Alex-Jordan  One of our instructors (or rather, one of his students) pointed out that Question 17 [in the section on continuity](https://opentext.uleth.ca/apex-standard/sec_continuity.html#subexercises-11) is not working correctly.

**Comment by Alex-Jordan** [comment]
It seems to me that the PG code is working, but there is a different issue here to work out.

The question really has 6 answer fields:

1. MC
2. essay
3. MC
4. essay
5. MC
6. essay

In this mode, the essay fields are suppressed. The user sees 1, 3, and 5. They make selections and submit. But I believe their answers are being compared to answers for 1, 2 and 3.

Could you try something? In your host course, go to Course Config. In the PG - Problem Display/Answer Checking tab, is the last item "Skip explanation essay answer fields"? If so, can you set that to True?

If that option is not there, then your server does not yet have the new feature to control explanation essay fields. You could get that from this PR to webwork2: https://github.com/openwebwork/webwork2/pull/1100 and this PR to pg: https://github.com/openwebwork/pg/pull/465

My belief/hope is that this will correct the issue. And then the documentation for setting up a PTX support course like this should include instructions to turn off explanation essays.

Of course the same issue might exist if there are just regular essay fields interspersed between quantitative answers. For that, some work will be needed on the javascript. If the above gets you through the current situation, update here, and then I'll open an issue for that JS work.

**Comment by sean-fitzpatrick** [comment]
I've been busy and set this aside and now I feel silly for not doing it sooner because that was a 15 second fix.
Changing the setting in the WeBWorK course fixed the problem.
