### ISSUE TITLE
Problem with Taylor Poly ln(x) figure fig_taypoly2c

### ISSUE THREAD

**Issue by grady** [APEXCalculus/APEXCalculusPTX#128]
It appears that the figure fig_taypoly2c, supposedly showing the 20th-degree polynomial of ln(x) is incorrect. It seems to be identical to the figure for the 4-th degree expansion of sqrt(x) fig_taypoly5c shown later in the section.

Also, in fig_taypoly5c at line 1131 the function is labeled ln(x) when it should be sqrt(x).

**Comment by sean-fitzpatrick** [comment]
Yes, I see that too. Good catch. I *think* I might have time to look at this tomorrow.
But I've frequently been wrong about what I have time for this semester. :-)

**Comment by sean-fitzpatrick** [comment]
Also there's an issue with how that figure is cropped: the label gets cut off. Not sure if that's happening at the cropping stage, or at the TikZ stage.

**Comment by sean-fitzpatrick** [comment]
This should be fixed once #134 is merged.
