### ISSUE TITLE
Proposed new example for sec_antider

### ISSUE THREAD

**Issue by grady** [APEXCalculus/APEXCalculusPTX#130]
This commit to my fork has a proposed new example for the antiderivative section: https://github.com/grady/APEXCalculusPTX/commit/6247ad5fe6e645fffc227eef0d4d9865b4450cbf

The text mentions the importance of the differential in the integral notation and specifies that it indicates the variable of integration, but this is never made explicit in an example. I propose a third example before the theorem presenting the list of antiderivatives. 

My usual example of this is to integrate the function s^n with respect to ds and then wrt dn, showing the indefinite integrals are different. I always do an example like this with my students to provide reinforcement that the differential does play a really important role in the notation.

I'm interested to hear some feedback on this before submitting a PR.

**Comment by davidfarmer** [comment]
I'll let others comment on the suitability, but a couple things about
the source and the style.

Make sure you actually compile the source before making a pull request.
You will find that you have a markup error.  (and maybe more than one,
I did not actually try to compile it).

It is good to choose a more semantic id than "ex_anti6".

At the start of the solution, I suggest that it is the meaning
of the integrals which are different.  It hides what is going on
to focus on the answer.

There are stylistic issues, such as using the "power rule" but not
referring to it explicitly.  What I do when I am the lead author
(which I am not for APEX) is to take care of such issues after the
pull request is accepted.

A math issue is that the n \not= -1 either needs to be repeated when
the answer is given, or one needs "cases".  This situation is a
perpetual headache!  One way around it is to start the statement with
"Suppose $s > 0$ and $n > 0$."  That actually helps in the second case,
since \log(s) is in the answer.

**Comment by APEXCalculus** [comment]
The text currently has two questions in the exercises that address this
issue, though not directly. In #26, we give \int e^\pi dx; in #27, we give
\int a dx.

I think the previous addition to the text stating that the differential
points out the variable of integration is important.

I'm concerned that this particular example has too much overhead & the
point of the problem could easily get lost. David points out the issue with
the cases, and his suggestion lead statement is (as usual) helpful. I
personally feel that the problem still has too much "baggage".

A two-fold alternate suggestion. First, make this an extended, exploratory
exercise. One reason for making this an exercise and not part of the main
text is that the vast majority of integration problems students will see
will have only one "letter"/variable. To point out the need to be careful
to identify the true variable of integration when they normally don't have
to worry about it is an unnecessary distraction, imo.

Secondly, let's consider changing the function to one that has fewer
special precautions. What about the function x^2 t^3? The point we wish to
get across will be made: one is to look at the differential to see what the
variable is, for the result will be different.

**Comment by sean-fitzpatrick** [comment]
I also like it better as an exercise, though I don't really have an opinion on exactly what the function should be.

As for the `xml:id` -- maybe a more semantic id is better, but this is consistent with the naming scheme for examples throughout the book. We inherited the original labels from the LaTeX version.

**Comment by APEXCalculus** [comment]
>
> As for the xml:id -- maybe a more semantic id is better, but this is
> consistent with the naming scheme for examples throughout the book. We
> inherited the original labels from the LaTeX version.
>
> In other words: Greg has some really lousy labeling conventions!!  :)
 I'd definitely be more descriptive if I could do it all over again...

**Comment by grady** [comment]
Sorry about the syntax errors, I still don't have a fully working development environment set up for the pretext. I had added this example to my own version based on the old tex files and thought it was worth discussing for an addition to the official new version.

Thanks for the tips on rewording @davidfarmer, those do improve the example significantly.

Perhaps my feeling that this is important issue is colored by the fact that in my field (statistics) it's extremely common to see one-dimensional integrals with one or more free variables present in the expression. Typically the free variables represent distribution parameters which have been left unspecified. However, I do agree that this is a departure from most of the examples in the book which only contain a single variable.

**Comment by sean-fitzpatrick** [comment]
I'm going through outstanding issues that can easily be addressed before running through a rebuild of both HTML and PDF.
@APEXCalculus were you still interested in including Grady's example?
If yes, either I can write it in, or @grady can send us a pull request. (Grady, unless you've been keeping your source up to date with upstream, maybe better to just attach the XML for that example here.)

**Comment by APEXCalculus** [comment]
I like the example, too, better as an exercise. I read through the section
again, looking for the ``right'' place to put the example. I don't think it
fits well - it will feel like a pedantic aside to many readers. However,
the point is good to make and is only alluded to in the Exercises. A more
explicit investigation is warranted.

I'd suggest the following exercise as the new #26 in the Exercises, right
before integrating \int e^\p dx  and also \int a dx, each of which deals
with the same issue.

Here's my attempt to code up the exercise.

<exercise>
        <webwork>
          <statement>
            <p>
              Consider the two integrals, <m>\ds \int s^n\,ds</m> and
<m>\ds \int s^n\,dn</m>.
              <ol>
                <li>
                  <p>
                    What is the difference between these two indefinite
integrals?
                  </p>
                </li>
                <li>
                  <p>
                    Evaluate  <m>\ds \int s^n\,ds</m>.
                  </p>
                </li>
                <li>
                  <p>
                    Evaluate  <m>\ds \int s^n\,dn</m>.
                  </p>
                </li>
              </ol>
            </p>
            <p>
              <ol>
                <li>
                  <p>
                    The indefinite integrals have different differentials,
i.e., different variables of integration.
                  </p>
                </li>
                <li>
                  <p>
                    <m>\frac{s^{n+1}}{n+1}+C</m>, <m>n\neq -1</m>
                  </p>
                </li>
                <li>
                  <p>
                    <m>\frac{s^{n}}{\ln s}+C</m>, <m>s>0</m>
                  </p>
                </li>
              </ol>
            </p>
          </statement>
        </webwork>
      </exercise>

**Comment by sean-fitzpatrick** [comment]
I've added this exercise a few commits ago, but forgot to close the issue. Closing now.
