### ISSUE TITLE
Problem 1.3.15

### ISSUE THREAD

**Issue by grady** [APEXCalculus/APEXCalculusPTX#141]
In the analytical limits section there is a problem that asks for a limit of f(x)^{g(x)}. Problem number 15 in my build, and the limit ends up being 2^0 = 1. The issue is that we don't have any limit property in the section that directly applies to this situation. The expression is neither a power expression nor an exponential expression, because both the base and exponent are functions.

This problem is answerable using the limit properties in the section, but it seems to require the use of the exp(log(...)) trick. Once you've algebraically rewritten the problem as equivalent to exp(g(x) * ln(f(x)) (which is only really known to be true in some neighborhood of 1, based on the info given), you then need to use the composition property, the continuity of log, the multiplication property, the composition rule again , and the continuity of exp in order to reach the correct conclusion about the limit. (Provided one uses only the results in the book so far.)  

The difficulty of this problem (if done correctly) seems way out of proportion to its place in the order of problems. For example the next three problems don't require any algebraic tricks to apply the limit properties, and only require the use of between 1 and 3 limit properties in order to reach the desired conclusion.

I like the problem, but it's a real challenge. I think it should be maybe moved closer to the end of the list of problems?

![Screen Shot 2021-09-01 at 16 53 22](https://user-images.githubusercontent.com/60004/131774048-1721124d-e1ca-4356-803e-a7a9c0ecd184.png)

**Comment by sean-fitzpatrick** [comment]
I feel like this one came up before and we considered making the answer "not possible to know", given the techniques currently at hand.

@APEXCalculus what do you think? Make this a question on its own?

**Comment by grady** [comment]
Yes, after reflecting on this I think that perhaps the original intention of the problem was that the answer was supposed to be "not possible to know" (unless a student is very clever and knew to try the exp-log thing), but at some point during the conversion to the WebWork, that the answer got "fixed" to be 1.

**Comment by APEXCalculus** [comment]
Grady gives me too much credit. That problem was written while I was
thinking like a Civil Engineering Freshman, and not like the Professional
Mathematician that I'm paid to be. The WebWork conversion didn't make the
answer 1; Hartman did from the start.

Or we can blame Sean. I'm good with that, too.

That problem should be changed. I propose changing it to 5^f(x). The
nuances of why we can't answer the original problem are too complex to be
introduced, and resolved, through the Exercises.

**Comment by grady** [comment]
I like the proposed replacement problem, since there is no other appearance of an exponential limit in the exercises so far. 

Maybe it should still be moved after the current problems 16 and 17 though. A careful answer to 5^f(x) requires the use of the composition property, so it would be nice to have a warm-up problem where use of that property is explicit. I propose to order these problems:

- f(x)g(x)
- cos(g(x))
- 5^f(x)
- g(5f(x))

Hopefully the use of cos() in the previous question will have directed their attention to the Special Limits theorem, which also includes the continuity of exponential functions.

**Comment by APEXCalculus** [comment]
That order makes sense to me; I say we go with that.

Thanks.

**Comment by sean-fitzpatrick** [comment]
Done. (On a branch) Will send a pull request once I'm sure I have nothing else to change.

**Comment by grady** [comment]
One other suggestion for this section: There are two theorems titled "special limits." Perhaps the first one would be better titled something more along the lines of "Limits of common functions".

**Comment by APEXCalculus** [comment]
How about "Special Limits" and "Special-er Limits"? Or "Special Limits, The
Sequel"?

The second set is aptly named "Special Limits" as they are not common
functions, nor expressions students would naturally find important. (Yet.)
Changing the first to "Limits of Common Functions" sounds like a good idea.

Thanks.

**Comment by grady** [comment]
Or perhaps take it in the dad joke direction with "Special Limits 2: Electric Boogaloo"?

**Comment by sean-fitzpatrick** [comment]
Closing, since this was fixed in #146
