### ISSUE TITLE
Problem 2.2.17

### ISSUE THREAD

**Issue by grady** [APEXCalculus/APEXCalculusPTX#147]
Problem 2.2.17 seems much trickier than the other ones near it. All of the others can be solved by just checking if slopes are positive or negative. But that is not enough here, a cursory examination of slope signs leads to the conclusion that either function could be the derivative of the other. 

It seems like the best option to determine the answer is to notice that both functions pass through (-1,-1), but they don't have the same slope there. So the original function is the one that actually has a slope of -1, which turns out to be f. But even that is kind of hard to determine without zooming in and grabbing a straight edge to put over the graph. Only once you've done that can you conclude that g is the derivative of f.  

I'm not sure if the intention of this question is to be tricky or not. If not, the functions need to be modified in some way so that it's possible to distinguish the derivative using sign information alone. Perhaps have f start to curve back up at the right instead of going to zero. 
 
![image](https://user-images.githubusercontent.com/60004/134756855-b40bddea-df3b-48d4-8545-03f65f6d3d4c.png)

**Comment by Alex-Jordan** [comment]
I remember thinking about this one when I was making WW code for it. I presume the pre-WW version has a similar issue.

I resolved it for myself by looking out closer to the ends. Like at 3, the value of f is close to 1/2. And that's not compatible with the red slope at 3. So there's another option than looking at (-1,-1), but it's still a tricky thing where signage is not enough and magnitude matters.

Note: we can make the image a nice tikz image now. It just takes time for a person to do it.

**Comment by grady** [comment]
As a more general matter, I really like this type of question. It seems to test the same overall concepts as asking for a rough sketch of a derivative, but without all of the difficulties that arise when you ask students to draw something.

The only thing I don't like is that a guess is correct with probability 1/2. In the test I just gave, I made the problem harder to guess by plotting 3 functions, the original and its first and second derivatives, and then asking for them to name the two correct derivative relationships that exist. That drops the guessing success probability to 1/15.

**Comment by Alex-Jordan** [comment]
There's a similar exercise in CLM with four curves to put in order: http://spot.pcc.edu/math/clm/section-higher-order-derivatives.html#exercise-257

**Comment by APEXCalculus** [comment]
I really like this problem, though when writing it I didn't consider the
eventuality of a computer grading the question.

I like it because, at the level of understanding students have at this
point, one should see that it could go either way. It turns into a
discussion point in class. I *think* I've kept it an odd numbered problem
so that the solution is in the back, which points out the difficulty:

Either g(x) = f ′(x) or f(x) = g′(x) is acceptable. The actual
answer is g(x) = f ′(x), but is very hard to show that f(x) != g′(x)
given the level of detail given in the graph.

I'm not sure how to turn that into a WW answer.

**Comment by grady** [comment]
@APEXCalculus Sounds good. As long as it is known and intended to be more difficult than its neighbors. I also ended up discussing it in class.

My take on these questions was worded like this (would need some tweaking to make accessible)

> Three functions are plotted below, in purple, blue, and orange. There are two correct statements of the form 
> > The [COLOR1] function is the derivative of the [COLOR2] function.
>
> What are they?

A few other off topic questions

- @Alex-Jordan What needs to be done to change these to tikz? can you point me to documentation?
- Are you all interested in this level of discussion of content? If not, I can keep it to errors only.
- Is github the preferred discussion forum? email? something else?
