### ISSUE TITLE
Index entry for Clairaut's theorem

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#148]
We should have an entry in the index for equality of mixed partial derivatives.
Should we also reference this as Clairaut's theorem?

**Comment by APEXCalculus** [comment]
Boy, I haven't thought about the index in a long time!

I'm fine adding entries as needed, for sure. Maybe the location could be
partial derivative -> equality of mixed partial derivatives

Not sure about giving it a name; according to Wikipedia (
https://en.wikipedia.org/wiki/Symmetry_of_second_derivatives) there are
several names associated with the concept. I'd never heard of any of them.

**Comment by sean-fitzpatrick** [comment]
Closing this. We don't need to attach a name to it. Originally I brought this up because I have a tendency to refer to this result as Clairaut's theorem, and a student complained that they couldn't find any such theorem in the book.
