### ISSUE TITLE
FTOC "differentiate the integral" exercises 

### ISSUE THREAD

**Issue by Alex-Jordan** [APEXCalculus/APEXCalculusPTX#159]
These exercises:
Exercisegroup 
https://opentext.uleth.ca/apex-video/sec_FTC.html#exercisegroup-95

are variants of the form:
Find F'(x) where F(x) is
int_{a}^{f(x)} g(t) dt

In all of these exercises, g is something that the students actually can antidifferentiate. Students can find correct answers by first integrating to get a formula in x, then differentiating. If a student does it that way, I think they miss the point. I feel like at least some (if not all) of these exercises should be such that it is unreasonable for them to antidifferentiate g. So they really know how to jump to the answer: g(f(x))*f'(x).

Should I change these exercises? Or just add more?

**Comment by APEXCalculus** [comment]
I would vote for 2 or 4 more where the antiderivative is hard/impossible to
find.

A nice part of the first set of 4 is that students can check their work via
antidifferentiation / differentiation. It can help solidify that the
process does work. After getting a good view of what the FTC is saying,
they can then move on to problems where it is harder to verify the answer &
must trust in their ability to follow the process.

**Comment by sean-fitzpatrick** [comment]
I'd also like to see a couple of the form F(x)=\int_{f(x)}^{g(x)} h(t) dt, where you need to use properties of integrals first, and then FTC+Chain rule

**Comment by sean-fitzpatrick** [comment]
I've added two more exercises. Pull request imminent.
