### ISSUE TITLE
open and closed

### ISSUE THREAD

**Issue by Alex-Jordan** [APEXCalculus/APEXCalculusPTX#165]
An open interval has the form (a,b).

And a closed interval has the form [a,b]. Except that [a,∞) is also an interval that is closed.

Should we use vocabulary like "open intervals and compact intervals" instead of "open intervals and closed intervals"? I am thinking in the context of "when the domain of a function is a closed interval...". 

For example this theorem is not true, even if we all know what is meant:
Theorem 3.1.4: The Extreme Value Theorem 
https://opentext.uleth.ca/apex-video/sec_extreme_values.html#thm_extreme_val

Or does APEX define "closed interval" in a special way? I looked a bit but I'm not sure where that would be defined. There is a definition for "closed" in the multivariable content that would imply [a,∞) counts as closed, but we already acknowledge that some multivariable definitions to not reduce to the single variable definitions just because n=1.

I'm not opposed to defining "closed interval" to be limited to intervals of the form [a,b], for pedagogical reasons to avoid a new term like "compact". If it's not there yet, should we add it to section 3.1?

Another thing is to meticulously examine each instance of the phrase "closed interval" and see if it really should say "closed interval of the form [a,b]".

**Comment by APEXCalculus** [comment]
Good catch.

Let's avoid new terminology like "compact". Here's a proposed solution to
the issue:

1. The first time we use the term "closed interval" - which I think is in
Section 1.5, Continuity - we make a marginal note that says something along
the lines of "In this text, when we use the term 'closed interval', we mean
an interval of the form [a,b], where a and b are real numbers. One may be
surprised to learn that intervals of the form [a,\infty), (-\infty, b] and
even (-\infty,\infty) are all also considered closed in advanced calculus.
While the mathematics supported by this definition of closed is
fascinating and important, it is beyond the scope of our purposes here."

2. Whenever we need a closed interval for a theorem, we explicitly use
[a,b] terminology. For instance, the MVT could read "Let f be a
continuous function defined on a closed interval I = [a,b]. Then f has both
a ..." Or eschew naming the interval and just use "Let f ... on a closed
interval [a,b]. Then f ... on [a,b]."

Thoughts?
Greg



(note to self: apex calculus error errata things to fix)

**Comment by sean-fitzpatrick** [comment]
This would be an easy fix. I agree that "compact" risks overloading students who already have too much terminology to tackle.
It would not take long to search the whole book for all occurrences of "closed interval" and where necessary, replace with "closed interval [a ,b]".

**Comment by sean-fitzpatrick** [comment]
I'm going to close this since I will forget to do it later, and we can move discussion over to the open pull request at #168 
I think it's resolved, pending review.
