### ISSUE TITLE
Units in Section 7.5 Problems

### ISSUE THREAD

**Issue by grady** [APEXCalculus/APEXCalculusPTX#166]
In the exercises for [Section 7.5: Work](https://opentext.uleth.ca/apex-video/sec_work.html#sec_work)

There are some unit issues in problems 6 and 8. In 6, the problem begins with a 50 centimeter rope but ends up asking for the work needed to pull up 20 meters. In 8, everything is consistently in centimeters, but unless we're discussing a model train city, the overall scale of things is way off.

6. A **50 cm rope**, with a mass density of 0.2 kg⁄m, hangs over the edge of a tall building. How much work is done pulling the entire rope to the top of the building? How much work is done pulling in the **first 20 m**?

and 

8. A 20 cm rope with mass density of 0.5 kg⁄m hangs over the edge of a **10 cm building**. How much work is done pulling the rope to the top?

I glanced over the rest of the problems, and these were the only weird ones that I noticed.

**Comment by APEXCalculus** [comment]
Looks like a conversion error from the LaTeX. The PreTeXt reads:
"A <quantity><mag>50</mag><unit prefix="centi" base="meter"/></quantity>
rope ..."

Can the unit prefix just be removed? I.e., just delete 'prefix="centi" '?

What's the advantage to using this system, and not just writing "50m"?
Does it help with webwork integration?

Maybe it is just an oversight, but in part (b) of that problem, we have
"How much work is done pulling in the first 20 m?",
without the units being referenced through <quantity>.

I was going to fix the issue by deleting two "c"s. But now I'll wait to
ensure I don't mess up the code.

**Comment by APEXCalculus** [comment]
All that makes sense, especially the screen reader part. I imagine units of
things like acceleration could cause readers & hearers fits.

I've pushed a fix removing the prefix part of the quantity tag.

**Comment by grady** [comment]
Problem 20 in the same section also describes a soda-can sized fuel tank. Maybe intentional, maybe not?

**Comment by Alex-Jordan** [comment]
I merged a commit (3847c94) that fixed a bunch of "cm" that should have been "m".

Git blame shows me this was not my doing :)

**Comment by APEXCalculus** [comment]
I'm pretty sure it was Sean's fault.

Thanks for the merge & other fixes.

**Comment by Alex-Jordan** [comment]
Well, I take it back. It's ultimately a result of the `quantity` syntax being so verbose that copy-paste gets a lot of use. But it is what it is.

**Comment by sean-fitzpatrick** [comment]
Could have been me! Mostly chiming in to note that I'm not ignoring things: GitHub notifications go to my work email, and we've been locked out for a month now.

**Comment by grady** [comment]
One more exercises issues I noticed a bit ago, It's in a different section, but I'm not sure it's worth a new issue:

In Section 7.1 (Area Between Curves), problem 28, the "triangle" that we are to find the area of is a line, since the coordinate (3,3) appears twice. This is carried over from the v4 PDF, so it might be intentional?

![image](https://user-images.githubusercontent.com/60004/157999045-c1c7fc32-13f5-41fa-b5c5-ee3f70a921f9.png)

**Comment by grady** [comment]
One more little thing I just noticed, actually from 7.5 as well. 

Figure 7.5.12 has a cropping issue with labels on the y-axis. The negative in -10 is missing.

![image](https://user-images.githubusercontent.com/60004/158002490-686f08d5-b6a7-4e27-b915-26625c211993.png)

**Comment by Alex-Jordan** [comment]
This cropping issue was mentioned before. It sounds like a PreTeXt issue more than an APEX issue. If I want to distract myself form grading calculus papers, I will look into this in the near future.

**Comment by APEXCalculus** [comment]
The area between curves problem is definitely a mistake in APEX & again in
PreTeXt.

The answer is supposedly 4, so it wasn't intentional to have a linear
triangle.

In the book, the three points are (1,1), (3,3) and (3,3). In PreTeXt, it's
(-1,1), (3,3) and (3,3).

It really doesn't matter how it's fixed - and the answer need not be 4, of
course. Having points (1,1) and (3,3) make the line joining them easy,
which is nice.

I think the points (1,1), (3,3) and (0,4) lead to an answer of 4. May be
able to make that fix in a while.

**Comment by sean-fitzpatrick** [comment]
This issue seems to have expanded to a few issues now. The bad triangles can be fixed by (a) changing the points, and (b) figuring out what the new answer should be. The water tank issue can be folded into #161 perhaps. The original issue seems to be fixed by Alex. So it seems we should:
- open a new PR to fix the triangles
- move the water tank over to #161 
- close this issue

**Comment by sean-fitzpatrick** [comment]
I think #196 should address the remaining issues here, and then we can close this.

**Comment by sean-fitzpatrick** [comment]
Closing as completed.
