### ISSUE TITLE
Sign error in Exercise 9.1.7 answer

### ISSUE THREAD

**Issue by grady** [APEXCalculus/APEXCalculusPTX#170]
The problem is to write the first few terms of a sequence, and in the answer all are off by a factor of -1. 

https://github.com/APEXCalculus/APEXCalculusPTX/blob/3847c94c2ee482b5dade7ab3135cc1479084bcf5/ptx/sec_sequences.ptx#L1684-L1699

Either L1690 needs to drop the minus sign, or L1695 needs to add a negative sign to every term.

**Comment by APEXCalculus** [comment]
The original problem includes the - sign, so it must have been dropped
somehow in the answer. So L1695 should change.

I may be able to make that quick fix tomorrow morning.

**Comment by APEXCalculus** [comment]
Created pull request fixing the minus signs. I'll let someone else confirm
I didn't do it wrong.

**Comment by sean-fitzpatrick** [comment]
I've merged your fix. It looks good to me.
