### ISSUE TITLE
Definition of Bounded Sequence

### ISSUE THREAD

**Issue by grady** [APEXCalculus/APEXCalculusPTX#172]
This is not an error, so much as a question/discussion about a definitional choice in the text: Definition 9.1.23: Bounded and Unbounded Sequences.

![image](https://user-images.githubusercontent.com/60004/162535927-9a3fbe1e-74ec-4d26-8f6c-dc7198314fd4.png)

I have a couple of thoughts about this definition. 

- First, I think it would be good to include a line saying "Any such number M is called an __upper bound__ ... and m is called a __lower bound__ for the sequence". (Then, in Exercises 29-34 I would also add the instruction to provide a bounding value along with any claim that the sequence is bounded.)

- Second, the definition of bounded uses a strict inequality, a_n < M for every natural number n. This seems like an odd choice to me, because using this definition of bounded, the real numbers lack the crucial "least upper bound" property. 

Not that I spend a lot of time talking about supremums in Calc 2, but someone usually brings up the idea of "least upper bound" during class. The present definition leads to some very strange results pretty quickly. (Constant sequences don't have a least upper bound??) 

I think it would be pedagogically valuable to make the inequality inclusive, so that it matches the definition of a bound that is found in upper-level math classes. Then you can at least truthfully answer that, yes, every bounded sequence has a least upper bound and a greatest lower bound, but we don't actually need that now, any bounds at all will work. (And also that you've stumbled on a really important idea that's beyond the scope of intro calc.)

Maybe there is a reason for this choice that I'm not seeing?

**Comment by APEXCalculus** [comment]
I'd like to say that there was a reason for the strict inequality, though
at present I have no idea what it was (if such a reason existed). I may
have intended students to not worry about the least upper bound but just
find any number that is larger than any value in the sequence to show that
it is bounded above.

I think adding the equality makes sense.

Adding the terms upper/lower bound is also good.

Both changes would require reading through the text and exercises to make
sure we use those terms where we should. Grady points out certain
exercises, and we should double-check examples in the text.




(A note to Greg to find this again: error errata)

**Comment by sean-fitzpatrick** [comment]
This will be fixed once #193 is merged.
