### ISSUE TITLE
Example 9.6.8 Typo

### ISSUE THREAD

**Issue by grady** [APEXCalculus/APEXCalculusPTX#174]
https://github.com/APEXCalculus/APEXCalculusPTX/blob/76c12cd0de97c17241388e1d0324246824ef2835/ptx/sec_power_series.ptx#L295-L302

Another unrelated issue from later in the chapter: [Example 9.6.8: Determining the radius and interval of convergence](https://www2.hawaii.edu/~gradysw/apex/sec_power_series.html#ex_ps2) 

![image](https://user-images.githubusercontent.com/60004/162900020-8b36b7e5-9cf8-4437-b929-5e3a5e293a90.png)

That middle line with n!x^n seems like it dropped in from a different universe... (Or maybe just part 4.) 

Fix: Delete line 299 in sec_power_series.ptx

**Comment by sean-fitzpatrick** [comment]
This will be fixed when #193 is merged. Thanks for catching it.

**Comment by APEXCalculus** [comment]
That middle line must have been a conversion error of some type - maybe it
got auto-corrected to that.

The line should be lim_{n\to\infty} |x|\frac{n}{n+1}.

So we shouldn't just delete the line; the middle step is informative.





(note to Greg: error errata)
