### ISSUE TITLE
Area for parametric curves

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#175]
Currently there is no discussion of area for parametric curves. I'm wondering if this was intentionally omitted, or if it's something that @APEXCalculus just didn't get around to adding.

Area for parametric curves is kind of interesting! Initially, you just have to convert the area formula from Calc 1: `\int_a^b f(x)\,dx` is just the integral of y dx. In parametric form, this becomes the integral of y(t) x'(t) dt.
Except now you have to pay attention to the orientation of the curve, and of course the curve may not be the graph of a function.

I think the most interesting case is that of a simple, closed curve. The area is given by `A = \pm \int_a^b y(t)x'(t)\, dt`, where the sign out front depends on orientation: minus for positively-oriented, plus for negatively-oriented.

**Comment by APEXCalculus** [comment]
I think finding area "under" parametrically-defined curves is really
interesting, especially in the case of closed curves. And as I was
surveying other texts while writing APEX, I saw this topic was missing from
most/all others.

It's hard to know, for sure, why this is the case. After pondering it for a
while, I came to the conclusion that the places where parametric equations
are most useful, the question at hand is not answered with an area.

So I left it out. I could be wrong about much of the above, of course. But
nothing else in Calc III depended on finding areas that way, and I couldn't
think of a truly useful application in engineering or physics apart from
"find the area of this cool shape."

**Comment by sean-fitzpatrick** [comment]
I think it's included in Stewart, which is not an argument in favour, but it does explain why it would be in my brain as an important topic.

There are a few "classical" problems that are solved this way, like finding the area under one arch of a cycloid.
The cycloid seems to occupy this place as a Very Important Curve in a lot of books. [Historically this is true](https://en.wikipedia.org/wiki/Cycloid) (along with epicycloids, hypocycloids, trochoids, etc.) but I'm not sure that's the case any more. Not everything that was a Big Deal in the 17th century remains so today :-)

One of my undergraduate Physics profs would beg to differ (if he were still alive). I remember much excitement about the brachistochrone problem, and the challenge to solve it -- posed by one Bernoulli, and solved by another.

But explaining that involves talking about calculus of variations, which somehow is no big deal in undergraduate physics, but outside the scope of undergraduate mathematics. (Maybe it's just no longer fashionable in math -- once the Euler-Lagrange equation was found, we decided to call it a day.)

If APEX ever reached the point where it included writing projects, this could be a cool one, because there is a **lot** of interesting history, and by finding the area under a cycloid, you get to solve a problem that stumped Galileo.

**Comment by sean-fitzpatrick** [comment]
I am realizing that there is little chance of me getting around to doing something with this, and since there's not a big appetite for it, I will close this issue.
