### ISSUE TITLE
what is (not) a power series?

### ISSUE THREAD

**Issue by Alex-Jordan** [APEXCalculus/APEXCalculusPTX#179]
Is the term "radius of convergence" defined only for power series?

If so, then a nitpick is that:
Theorem 9.6.7: The Radius of Convergence of a Series and Absolute Convergence 
https://opentext.uleth.ca/apex-video/sec_power_series.html#thm_abs_power
applies that term to a series that is not a power series.

Or should I interpret
sum a_n |x - c|^n
as the power series
sum a_n y^n
being evaluated at y = |x - c|?

Is item 4 here:
Example 9.6.8: Determining the radius and interval of convergence 
https://opentext.uleth.ca/apex-video/sec_power_series.html#ex_ps2
a power series?

The definition:
Definition 9.6.6: Radius and Interval of Convergence 
https://opentext.uleth.ca/apex-video/sec_power_series.html#def_radius_converge
sounds like it wants that term to only apply to power series, since it refers to the R in:
Theorem 9.6.4: Convergence of Power Series 
https://opentext.uleth.ca/apex-video/sec_power_series.html#thm_radius_converge

If all seems fine here then never mind. An alternative is to rephrase Theorem 9.6.7. Or maybe remove it. I think I understand that the goal is to convince students it's right to start looking at 
sum |a_n (x - c)^n|
Then APEX's version of the Ratio Test requires positive terms, so now you can use the Ratio Test on this other thing that is not a power series. I think there must be a concise but clear way to deliver that message.

**Comment by APEXCalculus** [comment]
First, Alex's question led me to discover some errors that need fixing:
- Item 4's problem statement in Example 9.6.8 (
https://opentext.uleth.ca/apex-video/sec_power_series.html#ex_ps2) doesn't
match its solution; they address two different problems. The statement is
new; the solution matches the original text.
- In the same problem, the solution to part 2 introduces " n! " in the
next-to-last step erroneously.

Alex raises an issue that has gone overlooked. I've done some searching
through texts in my office to see what others did & what I was thinking at
the time of writing. Stewart and Larson/Edwards define the Ratio Test by
using the absolute value, hence skip this issue. I don't recall why I chose
to write the Ratio Test as requiring positive terms. Thomas has a similar
Ratio Test as Apex, then somewhat skirts the issue when finding the radius
of convergence.

I can easily be wrong about this, but it seems that finding the radius of
absolute convergence leaves open the possibility that there is a larger
interval of conditional convergence (beyond including just endpoints).
Consider the sum of x^n / n. We know this converges absolutely on (-1,1).
We can also show it converges conditionally at x= -1. It seems to me that
there is a question of whether it could converge conditionally for some
other values of x near -1, such as x = -1.001. We can apply various tests
to show it doesn't, but having the troublesome Theorem 9.6.7 tells us we
need only look at (-1,1) and its endpoints.

It isn't terribly concise, but we could restate the theorem to parallel Thm
9.6.4. Here's a draft.

Let a power series \sum_{n=0}^\infty a_n (x - c)^n be given. The one of the
following is true of the series   \sum_{n=0}^\infty |a_n (x - c)^n|:
   1. The series converges only at x=c.
   2. There is an R > 0 such that the series converges for all x in (c - R,
c + R) and diverges for all x < c - R and x > c + R. Moreover, R is the
radius of convergence of \sum_{n=0}^\infty a_n (x - c)^n, and we also refer
to R as the \emph{radius of convergence} of \sum_{n=0}^\infty |a_n (x -
c)^n|.
   3. The series converges for all x.

Thoughts?
Thanks.
Greg



error errata apex calc

**Comment by davidfarmer** [comment]
I think the proposed expansion of Theorem 9.6.7 is not helpful
because it is cumbersome and probably does not provide any practical
improvement.

How is this for an alternative:

On any open interval, the series XXXX and YYYY either both converge
throughout the interval, or both diverge on some portion of that interval.

Followed by a note:

Theorem 9.6.7 says that both series converge for the same values of
$x$, except possibly at the endpoints of the interval of convergence.


Or maybe the note should be the theorem?

**Comment by Alex-Jordan** [comment]
I'd be fine leaving the APEX Ratio Test as it is (requiring positive terms). After years of using Stewart, I like the APEX way. It makes the Ratio Test more akin to the other basic tests. Stewart and others' use of absolute value with the RT always seemed artificial to me, designed to streamline the power series stuff later. Which is good, but still feels artificial. But if someone wants to do the work to really change that, and it's OK with Greg, I do not object. 

Is it important to allow the Root Test to be used to establish a radius of convergence? That is not in our curriculum, so we do things entirely with the Ratio Test. I covered this in class today, and my approach was Ratio Test-specific. A short version:

Suppose Σ a_n (x - c)^n is a power series. Where is it convergent? To start, let's ask where is it absolutely convergent. So we look at Σ |a_n (x - c)^n| instead for a bit. If we find:
lim ...  = lim |a_{n+1}/a_{n}  (x - c)|  = L|x - c|
then using the Ratio Test, the series is absolutely convergent when L|x - c| < 1.

What if you have an x with L|x - c| > 1? Well then for large n, you have |b_{n+1}| > |b_n|. That is, the terms of Σ a_n (x - c)^n are growing in absolute value. So they cannot be converging to 0, and therefore Σ a_n (x - c)^n diverges by the Test for Divergence.

This settles that 1/L is the radius. And it remains to look at the endpoints more closely. I think the paragraph right above this one is what can get you out of the issue Greg raised without saying a ton. It calls back to the Test for Divergence.

**Comment by APEXCalculus** [comment]
I'd rather not change the Ratio Test. I agree with Alex that positive terms
echo other tests; also, by changing the definition, there will be ripple
effects that I think will be difficult to track & correct.

Alex's logical progression is essentially what Thomas does. It is solid
logic, but feels like we are taking another step with the Test for
Divergence.

David's comment makes me wonder: what if Thm. 9.6.4 is simply rewritten to
include both the power series & the series of the abs. values of its terms?
As in,
"Let a power series \sum a_n(x-c)^n be given. Then one of the following is
true for both \sum a_n(x-c)^n and \sum |a_n(x-c)^n|:  ...  "

In terms of proof, which we skip, this is biting off a lot in one proof:
that the convergence is the same AND that one of the three results applies.
But it may be a quick way of addressing the issue.

**Comment by sean-fitzpatrick** [comment]
What if we do the following:

- Keep Theorem 9.6.4 (Convergence of Power Series) as is.
- Keep Definition 9.6.6
- After Definition 9.6.6, add a brief discussion similar to what Alex has above (not a formal proof, but a plausible explanation) where we note how the ratio test can be used to test for absolute convergence, leaving only the endpoints in question
- Delete Theorem 9.6.7. In its place, add a Key Idea, titled Determining Radius and Interval of Convergence
- Update Example 9.6.8, which we have to do anyway, to fix the flaws in the solution, and get rid of the absolute value in part 4

**Comment by APEXCalculus** [comment]
I can agree to Sean's suggestion.






(note to self: error errata  / thing to fix)

**Comment by sean-fitzpatrick** [comment]
It looks like Example 9.6.8 was fixed at some point, so it remains to add Alex's discussion and change Theorem 9.6.7 from a theorem to a key idea. I can do that now and then I think this is done. I'll close for now -- if my changes don't address the issue feel free to reopen.
