### ISSUE TITLE
Counters in the non-video version of the book

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#180]
I just noticed the following issue:

If we want to make a version of the book without videos, we use custom XSL to replace anything involving videos with empty templates.
This succeeds in removing videos from the book in HTML. (In LaTeX as well, I think, although I haven't build non-video PDF.)

But it doesn't remove the counter!

If the book has a figure/video, using XSL to kill the video gets rid of it, as well as the figure containing it.
But the counter still gets incremented.

I suspect that this won't be the case in LaTeX: if there is no figure in the source, then nothing gets added to the counter.
That would mean that numbering doesn't align between video and PDF.

(Also, it's just a bit weird in HTML when the counter seems to skip forward for no reason.)

**Comment by sean-fitzpatrick** [comment]
Right. When the videos are part of an exercise solution, I've put the video there on its own, with no wrapping figure.

But there are other videos: most sections have a video introduction, and often there's a video to explain a theorem or definition.
Those are in figures so I can add a caption, like "Video introduction to Section 3.4"

**Comment by APEXCalculus** [comment]
Do videos need to be inside Figures at all? There's a video right after
9.6.4, numbered 9.6.5. Then in the solution to Exercise 9.6.8, there's
another video, which is unnumbered. Ultimately, I'd say we should go all-in
with one method: either all videos are numbered, or none are.

It does not strike me as odd to have an unnumbered video, though I suppose
referencing it would be more difficult. Have edits ever been made to the
text to reference a video? I'd think not - the videos probably don't ever
contain new content, just more explanations of the text content.

I prefer unnumbered videos. In the print version, we can make a stand-in
Chapter 8 that is 1 page long that says "look elsewhere for this content."
Then that would be the only place in the printed text where the numbering
skips. Captions/titles for the videos are nice, though. When contained in
an Example Solution, it is pretty clear the video explains the solution.
Elsewhere, it may not be clear if a video is explaining a Thm/Def that
preceded it, or introducing content to come, etc. A title would be great.
Can we create unnumbered titles? Is there a PreTeXt equivalent to the " * "
versions of environments?

**Comment by sean-fitzpatrick** [comment]
I think the answer is no: we can't have a title/caption without a number. I believe Rob and/or David have some strong opinions about this.

There are a couple of spots in the book where a video is preceded by a short paragraph introducing the reason for the video. (There is a mechanism in place to kill these paragraphs if the book is made without video.)

**Comment by APEXCalculus** [comment]
That mechanism would be the solution in my mind to this issue: each video
is preceded by a short sentence stating what the following video covers.

"The following video works through the steps of this Example."
"The following video explains further Definition XYZ and Theorem ABC."

Etc.

I imagine that would take a lot of time to implement, right? Not hard, but
there are lots of videos.

**Comment by davidfarmer** [comment]
I think the "short sentence prior to each video" idea is
contrary to the philosophy of PreTeXt.  That is not structured
content: the sentence makes no sense without the attached video,
but (other than the very fragile connection of being adjacent
and having to assume it is always there) the attachment is not
explicit in the source.

We need an official way of having something like an un-numbered
figure, or a caption on a "bare" video.

I'll see if I can articulate the issue on pretext-dev.

Please prompt me if I take too long.

**Comment by sean-fitzpatrick** [comment]
Currently there are a few instances where there's a paragraph preceding a video; these are cases where I happened to have recorded a video that didn't directly correspond to an element of the textbook, such as an additional example that is done as a video, but not in text. Then there would be something like, "An additional example is explored in `<xref ref="vid-foo"/>` below."

Where these occur, I have them in a paragraph with an `xml:id`, like `<p xml:id="vidintro-foo">`.

Previously, we were using XSL to kill these paragraphs: there is a line like 
`<xsl:template match="p[starts-with(@xml:id, 'vidint')]" />`

But later today I'm opening a pull request that does two things:
1. Set up APEX for building with the CLI
2. Set up versioning for two options: color/print, and video/no video

Now those paragraphs look like `<p xml:id="vidintro-foo" component="video">`

If the publisher file contains `source/versions @include="video"`, then those paragraphs (and the corresponding videos) are included. Otherwise, the videos are left out.

**Comment by sean-fitzpatrick** [comment]
@davidfarmer I mentioned the idea of videos with captions on the pretext-dev thread titled "Design Discussion, 2D containers".

**Comment by sean-fitzpatrick** [comment]
I've also just added a new thread on pretext-dev, since the old one has gone stale.

**Comment by sean-fitzpatrick** [comment]
Since the issue of counters is settled by using versions/components, I'm going to close this and continue the remaining discussion (which is design-related) on #188 .
