### ISSUE TITLE
Informal definition of the limit

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#184]
Right now, there is no informal definition of the limit in APEX. (I suppose one could argue that a definition cannot be informal...)

A lot of APEX users tend to omit section 1.2. Would it be (un)reasonable to add an informal definition at the end of Section 1.1?
I could use PreTeXt's versioning feature to assign it to a component, so that it is only included if we are publishing the book for someone who does not want to teach the epsilon-delta definition.

In fact, we could use components to also control how we define one-sided limits and limits involving infinity.
Our classes usually skip epsilon-delta, and then students get confused/scared when they see the formal definitions in Sections 1.4 and 1.6.

It would be relatively straightforward to have parallel definitions assigned to "formal" and "informal" components, and then select one of these using the publisher file.

**Comment by sean-fitzpatrick** [comment]
Mostly wondering if @APEXCalculus has any objection to this.

This would end up in a component, to be included only if selected in the publication file.

Most likely I would do something like:

- add informal 'definition' in Section 1.1, with `component="informal"`.
- where epsilon-delta definitions appear in Sections 1.4 and 1.6, add a `component="formal" attribute, and then add corresponding informal definitions with `component="informal"`.
- building the book with `include="formal"` in the publication file would produce the same result as now. Building with `include="informal"` would use informal definitions instead.

There are no places outside of sections 1.4 and 1.6, respectively, where the formal definitions are cross-referenced,
so changing these definitions won't affect later content. The only discontinuity I can think of is that the videos I recorded are done for the formal definitions currently in the book.

I could also leave the definitions as-is in those sections, and add asides (that would only be included if the 'informal' component is selected) explaining things informally.

**Comment by APEXCalculus** [comment]
Back from holiday and trying to get caught up on issues that I can help
with.

There is an informal explanation of the limit in Section 1.1, here:
https://opentext.uleth.ca/apex-calculus/sec_limit_intro.html#p-40. And
section 1.2 opens with three or four informal definitions of the limit.

So is the question really about adding a new element to the book? As in, we
have Definitions, Key Ideas, Theorems; do we want to add Informal
Definitions? Or are you advocating to put the informal definitions from 1.2
into the end of 1.1, but in such a way we can easily exclude it?

I'm fine putting in an informal definition at the end of Section 1.1. There
are already 2 summary-type paragraphs there; we could precede those with an
informal def. It could read something like

"This section introduced the mathematical concept of the limit. We have not
yet formally defined what we mean by a limit, but a basic understanding of
the limit is this: given a function $f(x)$, we could say
$$\lim_{x\to 2} f(x) = 5$$ if, for values of $x$ near 2, the values of
$f(x)$ are near 5. However, this understanding is incomplete as the term
"near" is ambiguous." We'll give a formal definition in the next section.

Proper understanding of limits ..."

What do you think?

**Comment by sean-fitzpatrick** [comment]
Things are probably fine as is. My experience, in classes where Section 1.2 gets skipped, has been that students freak out a little bit when they encounter things like the epsilon-N definition for limits at infinity.

What about if we added an aside next to those definitions (which could be set up so that they are only included if a publisher chooses to do so), stating something like, (next to Def. 1.6.2 in this case)

"In case your course did not cover Section 1.2, what this definition is saying is that the value of f(x) can be made as large as we want by choosing a value of x sufficiently close to c."

**Comment by APEXCalculus** [comment]
An aside, which could be turned off, sounds fine with me. I think I'd
prefer them to be turned off. That may be the simplest solution.

In the case of Def 1.6.2, the following paragraph (
https://opentext.uleth.ca/apex-calculus/sec_limits_infty.html#p-1343) ends
with an informal definition. That sentence could be altered to omit the "In
other words" and replace them with "This leads us to an informal definition
of $\lim_{x\to c} f(x) = \infty$: if we get close enough to c, we can make
f(x) as large as we want."
