### ISSUE TITLE
Missing sections

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#2]
Right now the PTX source only covers up to Chapter 6 - techniques of antidifferentiation.
I thought the section on one-sided limits was missing, but it's there. However, it's under the name sec_limits_continuity.ptx (there is a sec_continuity.ptx file for the section on continuity).

If there's no objection, for ease of searching, I might suggest including chapter hints in the naming scheme for sections. I notice that the numbers in Greg's file names were stripped. Not sure if that's necessary/intentional -- the leading chapter numbers helped with organization.

I can do renaming, but we'll still need an initial conversion on the missing chapters.

**Comment by davidfarmer** [comment]
If there are other sections to be converted, just let me know
what version and which file to use.

David

**Comment by sean-fitzpatrick** [comment]
I will let Greg confirm, but:
Either the master branch of this repo, or of APEXCalculusV5 (they're identical right now).
Master file is Calculus.tex

**Comment by APEXCalculus** [comment]
If this isn't too late:
master file is Calculus.tex. I think (?) we decided to do everything in the
APEXCalculusPTX repository. But in terms of finding the file, they should
be the same in both places.

As far as naming conventions go, putting at least chapter numbers back in
seems useful to me. Some of my old filenames aren't the most intuitive, but
should be reasonably functional.

Looking over the pull request now.

**Comment by sean-fitzpatrick** [comment]
Resolved with PR#4 from David. Thanks, David. Looks like everything is there.
I've edited two sections so far. I expect the remaining sections from the previous conversion are identical. I'll copy the missing sections into the /ptx folder and then we're set.
