### ISSUE TITLE
Some arc length exercises involve functions that are not differentiable on a closed interval

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#200]
From Larry Riddle, via email:

Theorem 7.4.3 for arc length requires that f be differentiable on the closed interval [a,b] and that f ' be continuous on the closed interval [a,b]. However, the functions in exercises 5, 7, 15, 17, and 18 do not satisfy those two requirements. In each case the function is not differentiable at one or both endpoints of the interval because the derivative does not exist (they all involve square roots). There are no examples like this in the text and no discussion that it might still be possible to compute the arc length in such a situation.

There is a similar situation with the surface area. Theorem 7.4.11 has the same differentiability and continuity requirements as for arc length. But the functions in exercises 32 and 33 do not satisfy those requirements (again, both functions involve square roots).

Perhaps these types of situations involving improper integrals are just addressed in the classroom when covering these sections, but some comment or example in the textbook might be helpful.

**Comment by APEXCalculus** [comment]
I thought we dealt with this a long time ago, but I can't find reference to
it in my email.

It would be instructive to go through the steps of the improper integrals
needed to compute the arc length (perimeter) of a half circle, as asked in
the exercises. Then the exercises that need improper integrals could be
flagged.

I'll make a note to myself to address this at some point.

Greg

error errata apex calc

**Comment by sean-fitzpatrick** [comment]
@APEXCalculus I have time to tackle these today. What is your preference:

1. change the exercises so that the integrals are not improper
2. add a warning of some sort that technically they're not covered by our theorems, but we do them anyway because the results are interesting

**Comment by APEXCalculus** [comment]
Perhaps a mix.
For #5 & 7, these problems need only have easily accessible answers. The
real work is setting up the integral and recognizing how to
simplify/integrate. So new bounds are most appropriate.
#5: change bounds to [1,4]; answer is 10/3.
#7: change bounds to [1,9]; answer is 157/3.

For #15, 17 and 18, the point is to know how to find the arc length of
common/important shapes, though the computation is difficult. Here I think
a note is appropriate.
Perhaps in the exercise instruction set we can add "Note: the three
problems containing functions with square-roots are improper integrals. In
these specific cases, the integrals converge and Theorem X.Y.Z can still be
applied."
(If you can shorten that note well, go for it.)

What do you think?

**Comment by APEXCalculus** [comment]
And use the same note for #32, 33? I forgot that above.

**Comment by APEXCalculus** [comment]
Depending on the order you read this, perhaps ignore my previous email in
lieu of the email about the numerical approximation of the arc length
problems.

**Comment by sean-fitzpatrick** [comment]
I've taken care of all but the numerical ones. I'll move over to the other issue for those, and close this one.
