### ISSUE TITLE
Progress update (August edits/publication complete)

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#202]
FYI, for @APEXCalculus and @Alex-Jordan and whoever else is interested.
And a prompt to inspect the results before approving the remaining pull requests (or requesting modifications).

Edits and updates are complete, and I've published all the various HTML and PDF versions to my server.
As usual, getting the PDF ready to go was a pain in the ass. (Details in the next comment.)

So you can inspect, comment, etc. here are the various versions:

- [HTML, without videos](https://opentext.uleth.ca/apex-calculus/)
- [HTML, with videos](https://opentext.uleth.ca/apex-video/)
- [HTML, for U of L regular calculus](https://opentext.uleth.ca/apex-standard/)
- [HTML, for U of L accelerated calculus](https://opentext.uleth.ca/apex-accelerated/)
- [PDF, colour, no video](https://opentext.uleth.ca/PDF/apex-novideo.pdf)
- [PDF, print, no video](https://opentext.uleth.ca/PDF/apex-novideo-print.pdf)
- [PDF, colour, QR codes for video](https://opentext.uleth.ca/PDF/apex.pdf)
- [PDF, print, QR codes for video](https://opentext.uleth.ca/PDF/apex-print.pdf)
- [PDF, colour, for U of L regular calculus](https://opentext.uleth.ca/PDF/apex-standard.pdf)
- [PDF, print, for U of L regular calculus](https://opentext.uleth.ca/PDF/apex-standard-print.pdf)
- [PDF, colour, for U of L accelerated calculus](https://opentext.uleth.ca/PDF/apex-accelerated.pdf)
- [PDF, print, for U of L accelerated calculus](https://opentext.uleth.ca/PDF/apex-accelerated-print.pdf)

There are also course-specific PDFs (7 colour, 7 print) obtained by cutting out the relevant parts.

**Comment by sean-fitzpatrick** [comment]
The main things that need to be dealt with while producing the PDF:

- adjusting the placement of margin figures, so they don't overlap or run off the page
- remembering to do this for print first (I didn't) because if a margin figure occurs at the page break, it gets the wrong page counter, and gets placed in the wrong margin. So these need to be moved one paragraph up/down
- adjusting tcolorbox width for some theorems/definitions where there's an equation that's too long for the standard box size
- in print, also adjusting the horizontal placement of these wider boxes if they're on an even-numbered page
- forcing some page breaks, but not as many as in the past
- identifying a few images/tables that get placed in the margin by the XSL, but really shouldn't be
- redoing the page layout for the gallery of polar curves (I've reproduced the original APEX layout, but this doesn't work in HTML)
- splitting up a couple of two-column layouts in the answers in the back, where there is overlapping text otherwise

Most of the work is dealing with margin figures. And it takes a long time, because each run of XeLaTeX takes about 5 minutes, and you often need to run it twice for changes to take effect.

**Comment by sean-fitzpatrick** [comment]
If everyone is happy with the output, I would suggest processing pull requests, and then we can close several open issues (including this one).

@Alex-Jordan suggested that we might not need the pull request that changes the publication files to use separate courses for WeBWorK builds. But those courses are already in place, and when you're trying to simultaneously build 4 HTML versions and 8 PDF versions, it turns out to be convenient to be able to separate your WeBWorK builds. ;-)

**Comment by APEXCalculus** [comment]
I'm good with the merge. I can wait until tomorrow morning to give others time to consider them. If I don't see objections, I can merge at approximately 6:30 am EST, which is way early for the west coast folk.

**Comment by sean-fitzpatrick** [comment]
You can leave the pull request to change the publication files for webwork until the end of the week. I think Alex wants to discuss this at the PreTeXt drop-in meeting on Friday.

**Comment by sean-fitzpatrick** [comment]
I've made all the progress I'll make for awhile, so closing this. :-)

**Comment by APEXCalculus** [comment]
#197 - "move videos in solutions ... " has a conflict that was perhaps
caused by another merge.

I merged the other 2 requests.

**Comment by sean-fitzpatrick** [comment]
One other comment from you showed up late, but fortunately I predicted the future and made the change you requested.
