### ISSUE TITLE
Increasing and decreasing functions

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#205]
I remember us having this conversation once, but can't find it among the closed issues/pull requests on GitHub:

In APEX 3.0, we define a function to be increasing if `x_1<x_2` implies `f(x_1)\leq f(x_2)`, and strictly increasing if instead we have `f(x_1)<f(x_2)`.

Currently we only have the strict inequality. This isn't consistent with what you'd find in most analysis textbooks, but I feel like there was a good reason for the change. Does anyone remember?

**Comment by Alex-Jordan** [comment]
I don't remember what was said before.

I feel that it is inconsistent with regular everyday English when a constant function is "increasing". So at this level, for pedagogical reasons, my preference would be that the definition for increasing used strict inequality.

Of course these things tend to have consequences downstream...

**Comment by sean-fitzpatrick** [comment]
We probably need to add an aside, either way. With the current definition, a warning that in future courses, things will be defined differently, or with the old definition, an aside that says something like "It might seem odd that, according to this definition, a constant function is both increasing and decreasing. However,...."

One of the people teaching Calc 1 with me right now is from Quebec, so learned everything in French. I guess it is less of a language issue in French; e.g. French 'positive' corresponds to English 'non-negative', so a constant being both increasing and decreasing isn't any more strange than 0 being both positive and negative.

**Comment by APEXCalculus** [comment]
I don't fully recall the discussion, but I think some relevant issues were:

- I made a distinction in 3.0 between increasing and strictly increasing.
Then never again did I revisit that distinction.

- To make matters worse, I used the term "increasing" when I generally
meant "strictly increasing". See the next point.

- We test for increasing by looking at where f'>0, meaning we actually look
for intervals on which f is "strictly increasing". But I just referred to f
as "increasing" on those intervals.

- Alex's argument of common-use language factored into the change as well,
I believe.

So we made the change to use only the term 'increasing', and added some
text to talk about how to handle cases such as f' > 0 on (a,b) and (b,c),
with f'(b) = 0. We also changed the wording in the exercises to have
students look for "maximal" intervals of increasing/decreasing, though I
don't think we use that word in the text.

I don't mind having our term be at odds with many other texts. We should
make a definition that suits us best, and when students actually
acknowledge the difference, it will reinforce the concept of "be sure to
define your terms before reaching conclusions." At the same time, my copies
of Thomas and Larson/Edwards both define increasing as we do. (I just
returned my borrowed copy of Stewart two days ago so I didn't check it.)

**Comment by APEXCalculus** [comment]
Overall, I like the aside.
I did some editing below to shorten it a bit. Shorter asides are better
than longer ones, imo. You don't have to accept it as it is; it's just a
suggestion.

<aside>
    <p>
      <alert>Caution:</alert> the definition given in <xref
ref="def_incr_decr"/>
      is not the one found in formal mathematics textbooks.
      Such texts define a function to be increasing on <m>I</m> if,
      for every <m>a\lt b</m> in <m>I</m>, <m>f(a)\leq f(b)</m>.
      (Notice how equality is allowed.)
      The condition <m>f(a)\lt f(b)</m> is then referred to as
<em>strictly increasing</em>.
      Similar definitions are made for decreasing and strictly decreasing.
    </p>

    <p>
      While this definition has certain technical advantages in a
proof-based course,
      it is also conceptually counterintuitive for many students.
      For example, with this definition a constant function would be
both increasing and decreasing!
      </p>

  </aside>

**Comment by sean-fitzpatrick** [comment]
Edits made. Pull request coming later today, along with a few other things.
