### ISSUE TITLE
Index entries on one line

### ISSUE THREAD

**Issue by davidfarmer** [APEXCalculus/APEXCalculusPTX#21]
Some places it has index entries with the opening and closing
tags on different lines.  Those should be on one line
(the prettyprinter puts those on their own line, with extra indentation)

Probably fix this with a script later.

**Comment by sean-fitzpatrick** [comment]
Yes, this depends on whether the index entry came from your conversion, or the old apex-mbx code.
The previous conversion attempt used now-deprecated index code; this was fixed by the fix-deprecations utility, but left as a multi-line entry.

**Comment by sean-fitzpatrick** [comment]
This was resolved with a commit yesterday on the housekeeping branch.
