### ISSUE TITLE
Adding historical (and possibly non-European) context to the book

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#212]
I'm curious if there is any interest in this: one of my students just submitted a final paper with the title, "A Discussion on the Historical Figures of Calculus, Excluding Dead European Men."

She pointed out that she managed to take three semesters of calculus, and learned plenty of names (Newton, Leibniz, Riemann, Taylor, Stokes, etc.) but not one of them belonged to a woman.

Her paper makes the case for including historical asides, and perhaps also an appendix, where we can include details on this. (E.g. we might mention that Cavalieri's principle was discovered more than 1000 years earlier by Zu Chongzhi.)

In Canada I suppose this would be considered "Decolonizing" the textbook. In the USA, maybe this is "wokeism" and therefore bad?

If it's something we think might be worthy of inclusion, I could probably find some students interested in doing the work as an applied studies course. (We're big on "experiential learning" here.)

**Comment by APEXCalculus** [comment]
Sean,
On a scale of 1 to 10, I think my interest in historical/personal anecdotes
about mathematicians is about a 4 or 5. On one hand, they can be
interesting asides. On the other, often these anecdotes say things like "He
made important contributions to topics X, Y, and Z", where most calc
students have no idea what X, Y and Z mean. I'm not sure the content is
worth the effort; we may be playing more to the calc teacher's interest
than the calc student's. I could be wrong.

I also have zero interest in associating my name in print/online to
political/social commentary. So when I read "I have a math-history paper
with the words 'excluding dead European men' in the title. Want to put some
of that content in your text?", my immediate reaction is "No." I know you
are *not* suggesting we only include historical asides of non
dead-European-men. I still get the heebie-jeebies, to use a clinical term.

I am very interested in seeing your student's paper if she is willing to
share. I am interested in her case for including historical context as well
as seeing the contributions of other mathematicians that are not Newton,
etc. And maybe that will change my mind about my first paragraph above.

Thanks.
Greg

**Comment by sean-fitzpatrick** [comment]
I guess her point is that every calculus book, including APEX, presents calculus as something that was developed exclusively by European men.

So if you're a woman, or a person of colour, there's an implicit message: "This is not for you."

This is not just a problem with calculus, of course. You could probably do an entire undergrad in math without learning something named after a woman, and it's not because there were no contributions by women; instead, it's that historically, we've chosen to ignore them.

It may not fit with the book, but it's an interesting point.

**Comment by Alex-Jordan** [comment]
Is it relevant that the excluded people are dead? I guess that is an allusion to a more overt colonial era.

A local colleague evolved David Lippman's Math in Society book into what we use here for that course.
https://spot.pcc.edu/math/mathinsociety/language_logic_rules.html
Every chapter opens like that with a biography.

When I was a student, I did not care about these biographies in textbooks. Yes, I think they were all white men with maybe one or two references to Noether. But personally, I was not interested in history. Greg's "4 or 5" would have been a "2 or 3" for me. Maybe now I am a little more intersted, but not much.

On the other hand I appreciate these recent efforts like in the MIS book above. I've witnessed it have a positive effect (self-reported) from local students of color.

I think I'm just sharing my thoughts here. No opinion on adding things to APEX proper. Sean, you could still see if there is local interest to write the bios and optionally include where you host?

**Comment by APEXCalculus** [comment]
A computer science colleague used to tease us math folk about how
nothing was new in calculus - "it hasn't changed for 200 years." I suppose
most of what is taught in freshman level math and science courses
was developed by people who are now dead.

I did a non-scientific poll of 2 faculty here. Our history of math prof
said her students weren't interested in biographies, much less her calc
students. The other described his interest in terms similar to Alex's.

So I'm still not particularly interested in pursuing this for the calc
text. And I am still interested in the student's paper. Optional inclusion
is, of course, an option.

**Comment by sean-fitzpatrick** [comment]
Fair enough!

The title came about from a classroom conversation. Somebody made the joke that there must not be any living mathematicians, based on what they learn.
(Several in this class are physics majors, and they hear about new physics in class regularly.)

Somebody else added that not only are they all dead, they're all white dudes as well. So that got one student (a fine arts major who does math for fun) wondering if she could find any examples of contributions to calculus that didn't come from this demographic. :-)
