### ISSUE TITLE
APEX logo not rendering in preface

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#213]
In the [preface](https://opentext.uleth.ca/apex-standard/apex-preface.html#pars-apex) there are a couple of places where the APEX logo is inserted as LaTeX code (with a lot of kerning). I think this was once fine, but it is certainly not working now.

In source, this is `<m>\apex</m>`, with the `\apex` command defined in the docinfo.

**Comment by sean-fitzpatrick** [comment]
Maybe this just needs to be replaced by an image? (Can we even do inline images?)

**Comment by APEXCalculus** [comment]
We can get fancy with inline images, but it's easier to just use APEX. That
would be my vote.

**Comment by sean-fitzpatrick** [comment]
This is slightly mysterious, because if I go to the [MathJax demo page](https://www.mathjax.org/#demo) and paste in the code for the APEX logo, it renders just fine. I don't know why it isn't working in PreTeXt.

**Comment by sean-fitzpatrick** [comment]
The suggestion from Rob and David is to write some extra XSL that would create an `<apex/>` element, modelled on the existing `<latex/>` element.

I think I could get this figured out in an hour or so. @APEXCalculus is it worth it? You earlier voted to just use APEX in regular all-caps. There are two places in the entire book where the `\apex` macro gets used, and they're both in the preface.

**Comment by APEXCalculus** [comment]
Just using APEX seems fine with me. On the website I use APEX throughout
unless I have a screenshot of something from the cover. If later we want to
revive the TeX-themed logo, we can. But it isn't all that important at the
moment.

**Comment by sean-fitzpatrick** [comment]
Fixed by direct commit in 0928f65
