### ISSUE TITLE
TOC depth

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#217]
Style question: I just realized that I've been setting the depth for the table of contents to 3 across all of my APEX builds.

The versions I build for use here include division into parts, like [this one](https://opentext.uleth.ca/apex-accelerated/apex-calculus.html)

But the [standard build](https://opentext.uleth.ca/apex-calculus/) does not have parts.

So on my version, the TOC shows Part, Chapter, Section.
On the others, the TOC shows Chapter, Section, Subsection.

Should the table of contents depth be set to 2 for the official versions, leaving out subsections? (I think probably)

**Comment by APEXCalculus** [comment]
Yes, I think Chapter and Section are enough.

**Comment by sean-fitzpatrick** [comment]
OK. Pull request coming momentarily. There is work in progress to have an expandable TOC, which makes this slightly moot. I think it will set the default level shown to readers when they first load the page, and then anyone who wants to can expand a section to subsections. In any case, the default should be depth="2".

**Comment by sean-fitzpatrick** [comment]
Change made in #218
