### ISSUE TITLE
Some exercises ask for Simpson's rule when it can't be applied

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#219]
There are some exercises on [arc length and surface area](https://opentext.uleth.ca/apex-accelerated/sec_arc_length.html#exercisegroup-146) that ask students to use Simpson's rule with n=4 to solve.

But Simpson's rule requires (if I recall correctly) the 4th derivative to be continuous on the closed interval over which we're integrating. (This assumption is not mentioned in the book.) Some of these exercises involve functions that are not differentiable at the endpoints of the interval, such as `\sqrt{1-x^2}` on `[-1,1]`.

Since Simpson's rule evaluates the function at the endpoints, it will necessarily blow up for these examples. Is that the point?
The book acknowledges that f'(x) is not defined at the endpoints for these exercises, but I don't see anything that advises students on how they should address this issue.

Note also that [Theorem 7.4.4](https://opentext.uleth.ca/apex-accelerated/sec_arc_length.html#thm_arclength) for the arc length formula assumes differentiability on a closed interval, so it is not even clear that the arc length formula should be valid for these examples.

**Comment by APEXCalculus** [comment]
Changes should be made to this section & exercise set.

A motivation for these examples is that once we know the surface area
formula, it is natural to apply it to common shapes. What's the surface
area of a sphere/ellipsoid? We can (maybe) set up an integral to find it.

The functions giving us these shapes fail the conditions of the Thm.,
though the resulting integrals do converge. When trying to approximate the
values of the integral using Simpson's Rule, we find we can't; the answers
in the back simply say "Simpson's Rule fails".

That was, in my best recollection, part of the point: spheres, etc., have
seemingly nice shapes but our current calc methods struggle to compute the
values of some basic traits. But the Exercise section is the wrong place to
make such a point. I should have put that in an example within the text,
where I can also explain the issues at hand.

I'll put this on my oft-ignored To Do list of things to edit.




error errata apex calculus

**Comment by Alex-Jordan** [comment]
I don't enjoy covering the standard integral approximation techniques because the curriculum and schedule here forces it to be rushed. I'd like to have a calculus class some day where there is more science of approximation applied throughout the course. In that hypothetical course, if we had the integral:

∫₀¹ √(1 + ¹⁄ₓ) dx

and we anted to use Simpson's Rule, well of course it can't be used. But we would examine how to "mellow out" the integral with the right substitution. In this case, x = (u − 1)² leads to:

∫₁² 2√(u² − 2u + 2) du

It's an equivalent integral but now Simpson's Rule can be applied.

There could be a subsection about how to strategically work out that helpful substitution, in this case x = (u − 1)².  But I think this is maybe too niche for a typical calculus course.

**Comment by sean-fitzpatrick** [comment]
I would definitely be interested in teaching that sort of thing, and I think that in the near future, it'll be a lot more important than many of the integration techniques, since these can be done quickly by a variety of free online calculators.

My Calc II course this term (which has students in our Engineering transfer program) is using APEX, but I'm doing weekly labs using Python via Jupyter notebooks.

Next week's assignment has them doing some integrals numerically; one of the problems brings in one of these integrals, has them (a) realize that Simpson's rule is no good, and then (b) write a routine to use the midpoint rule instead.

PS: I never learned about any of these helpful substitutions, so now I want Alex to point me to a reference.

**Comment by Alex-Jordan** [comment]
I don't know that I could find a reference, but I can run through an example. Let f and g be inverses, and you will eventually substitute x=f(u), u=g(x) once you figure out what f and g really are. With the above example:
∫_{g(0)} ^{g(1)}  √(1 + 1/f(u)) f'(u) du

The original issue was that 1/x ~ 1/0 as x goes to 0. So you still must have f(u) approaching 0 as u goes to g(0). But bring f'(u) inside the radical, and that term inside the radical is 
[f'(u)]^2/f(u)
So now as u goes to g(0), maybe the numerator also goes to 0 and that "mellows out" the whole thing and prevents it from blowing up. So find a solution to:
f(u) ~ f'(u)^2
for u near g(0). With both sides approaching 0 as u approaches g(0).

You could run with something more specific:
f(u) = f'(u)^2
and either solve the differential equation, or if students can't do that yet, still reason out that we must be looking for f(u)=c(
u-k)^2 for some c, k. I don't even think I chose the best most straightforward c and k before. You could just run with f(u)=u^2 and then you get:

∫₀¹ √(1 + ¹⁄ₓ) dx
= ∫₀¹ √(1 + 1/u²) (2u) du
= 2 ∫₀¹ √(u² + 1) du

with no blowing up.

**Comment by sean-fitzpatrick** [comment]
Returning to this issue just now. (To be fair, I am returning to **all** the issues just now...)

The technique suggested by @Alex-Jordan are great. But I don't know if there's room to include them.
@APEXCalculus do you have any interest in an exercise set with an instruction along the lines of:

For the following integrals:
(a) Explain why Simpson's rule can't be applied
(b) Apply the substitution x=f(u)
(c) Evaluate the resulting integral using Simpson's rule

If yes, we could try to come up with a couple.

For the existing exercise set, why don't we just change the instructions on the exercise set to "use Simpson's rule... or explain why it cannot be applied."?

**Comment by sean-fitzpatrick** [comment]
I will tackle this (and the arc length issue) tomorrow. Then I think I am going to pause edits for the summer and get to work on building PDFs.

**Comment by sean-fitzpatrick** [comment]
OK, this is done. It also turned out that there were two flaws with the exercises in this section we had overlooked:

1. There were webwork tags, but no webwork code. So the problems all had Activate buttons, but there was nothing to do once you activated.
2. All the problems had a `<solution>` that was really an `<answer>`. That meant none of these were getting answers in the back.

Pull request coming soon.
