### ISSUE TITLE
Comparison for improper integrals with infinite range

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#221]
Currently the textbook states both direct and limit comparison results for improper integrals, but only for those where x goes to infinity.

For integrals with infinite range (e.g. \int_0^1 \frac{\sin(x)}{\sqrt{x}}\,dx) there is no limit comparison test (that I'm aware of) but direct comparison can still be used.

I think this needs to be mentioned. 
Otherwise, students may make one of two assumptions:
1. there is no comparison test that can be used in this situation
2. both types of comparison test can be used

**Comment by APEXCalculus** [comment]
Yes, we should mention the direct comparison option for these types of
integrals.
I'll add this to my list.
Thanks.


error errata apex calculus

**Comment by sean-fitzpatrick** [comment]
On more careful inspection, there is a paragraph near the end that mentions comparison for integrals with infinte range; it states that this case is more difficult, and omitted from the book.

I added an aside stating that if you really do need to do comparison for an integral of this type, you should stick with direct comparison, as this is less prone to pitfalls. If this is OK, we can close this issue.

Here is my added text:

> If you do need to use comparison for an improper integral with infinite range,
> it is generally wise to stick with direct comparison.
> Direct comparison will continue to work in more or less the way you expect;
> however, limit comparison is much more subtle, and prone to incorrect conclusions.

**Comment by APEXCalculus** [comment]
That sounds good to me.
I looked at this recently when I was addressing my list of typos, etc. I
made a note to myself to "backburner this" as I didn't see a concise way of
presenting it. The comment and your note are enough to say "this is a
thing, but perhaps tricky" and only the most persistent will chase it down.

Thanks.

**Comment by sean-fitzpatrick** [comment]
OK, great! Last semester I noticed that some students were trying to use limit comparison for improper integrals with infinite range, but they were still taking the limit as x goes to infinity! So we had to discuss why that didn't make much sense in that context.
