### ISSUE TITLE
Extra XSL is broken for videos

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#227]
Awhile ago there was a brief announcement about how the CLI handles interactive elements.
I didn't realize that this appears to have included a major rewrite of how YouTube videos are handled in PDF.
(In particular, QR codes are now generated externally and imported as images, rather than being part of the tex source.)

It seems like the XSL that's supposed to put videos in a margin figure is being ignored, and there are some problems with broken LaTeX. I'll see what I can figure out.

**Comment by sean-fitzpatrick** [comment]
Previously our XSL was detecting over 1100 figures, images, tables, etc. for location in the margin.
Now it is catching about 500, and the LaTeX is broken. So there must have been some big changes upstream that I didn't catch.

**Comment by sean-fitzpatrick** [comment]
@Alex-Jordan it looks like this will not be a quick fix. I think 80% of our XSL for putting things in the margin is no good anymore...

**Comment by Alex-Jordan** [comment]
I'll take a look when I can, but it may be a few weeks when the term is over here.

**Comment by sean-fitzpatrick** [comment]
I'm hoping to get to drop in more often starting on Friday, and I'll see if Rob can help. Videos are done in assembly now, which makes things trickier.

**Comment by sean-fitzpatrick** [comment]
Fixed once #234 is merged.
