### ISSUE TITLE
prime spacing in section parametric_eqn

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#242]
I noticed while adding exercise labels that in the section on parametric equations (in the discussion of smooth curves), we are missing the thin space between the functions and the prime mark for the derivative.

Adding an issue since that change should go in a different PR.

**Comment by APEXCalculus** [comment]
Are you referring to instances of x' and y'? Or other cases?

I am looking at the pdf and don't see anything egregious. The Calibri/Carlito font didn't handle f' well, but did ok with things like g', hence the coding of \fp and things like \vrp. 

Am I looking in the wrong place?

**Comment by sean-fitzpatrick** [comment]
I am looking at the [HTML version](https://opentext.uleth.ca/apex-calculus/sec_param_eqs.html#def_smooth), in the section on smooth curves. I see lack of spacing for g', x', and y'. Spacing for f' is OK since it's typeset using `\fp`.

I haven't looked at the PDF -- I usually only open the PDF once a year in the summer, when I'm trying to get ready to ship PDF for the year!

**Comment by sean-fitzpatrick** [comment]
This seems to be more pervasive but it's not clear to me how best to proceed.
@Alex-Jordan pointed out that manually adding space is bad for accessibility in the HTML version.

I also noticed that in the docinfo file, the command \fp is currently just doing f' rather than adding any spacing.

There are macros defined for y' and g' but they're not widely used in the book.

For someone using a screen reader, I'm not sure what is better:
1. Replace all instances of \fp with f' (and if necessary, live with spacing issues sometimes)
2. Replace the \fp macro with something more semantic, like \fprime

I need to learn a bit more about how someone using a screen reader interacts with the math content.

**Comment by sean-fitzpatrick** [comment]
On a branch I have done some preliminary work: there are macros in place for `f'`, `g'`, `x'`, and `y'`, and applied for all instances of these in the book. (Possible I missed a few.)

But I need to look at what other constructions are there: it would be good to do this systematically, and catch all derivatives in the book.

**Comment by sean-fitzpatrick** [comment]
I left that branch for too long and a clean merge is no longer possible. In any case I don't think it was necessary.

That said, it would be useful at some point to go through and ensure that we're consistent about using macros for prime notation. E.g. in some places you can find `\fpp` and in others, `\fp'`. I guess they are equivalent, but still...
