### ISSUE TITLE
Make Exercise group for L'Hopital's Rule

### ISSUE THREAD

**Issue by APEXCalculus** [APEXCalculus/APEXCalculusPTX#243]
Exercises 9 - 54 in the section on l'Hopital's Rule ( 
https://opentext.uleth.ca/apex-accelerated/sec_lhopitals_rule.html#exercisegroup-80) all repeat the instruction of "Use l'Hopital's Rule to evaluate the given limit." That instruction should be in the Exercise group instructions.

I'd do it myself now, but my PreTeXting abilities are a bit raw at the moment.

**Comment by sean-fitzpatrick** [comment]
This should be solved by #249
