### ISSUE TITLE
Replacement term for "scalar product"

### ISSUE THREAD

**Issue by APEXCalculus** [APEXCalculus/APEXCalculusPTX#246]
Def. 11.2.7 defines the product of a scalar and a vector as a "scalar product." However, if you google that term, you'll see that most places use that term as synonymous with "dot product", a fact that has me incredibly surprised.

I'm considering changing the term to "scalar multiplication". That is, the line in the def. will read "The scalar multiplication of c and v is the vector ... ". 

What do others think? 
The good news is this term seems to only be used in this definition, so there isn't much to change.

**Comment by Alex-Jordan** [comment]
If I hear "scalar product" without context, yeah, I think my head goes to some sort of inner product that is producing a scalar as its result from multiplying two vectors together.

I'm good with "scalar multiplication".

**Comment by sean-fitzpatrick** [comment]
I would strongly agree with this change :-)
"scalar multiplication" for the process, and "scalar multiple" for the result of the process.

**Comment by sean-fitzpatrick** [comment]
This is resolved in #247. I haven't merged yet, because I want @APEXCalculus to revert some of the Asymptote code first.
