### ISSUE TITLE
WW graph randomization leads to invalid TikZ

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#248]
For @Alex-Jordan but I am going to see if I can fix it myself. The following problem is in `sec_lilmit_infty.ptx`:

```
        <exercise label="ex-limit-infinity-use-graph-2">
          <webwork xml:id="ex-limit-infinity-use-graph-2">
            <pg-code>
              @a=(1..9)[NchooseK(9,2)];
              $f=Formula("1/((x-$a[0])(x-$a[1])^(2))")->reduce;
              $L[0]=($f->eval(x=>$a[0]-0.1)>0)?Compute("inf"):Compute("-inf");
              $L[1]=($f->eval(x=>$a[0]+0.1)>0)?Compute("inf"):Compute("-inf");
              $L[3]=($f->eval(x=>$a[1]-0.1)>0)?Compute("inf"):Compute("-inf");
              $L[4]=($f->eval(x=>$a[1]+0.1)>0)?Compute("inf"):Compute("-inf");
              for my$i(2,5){$L[$i]=($L[$i-2]==$L[$i-1])?$L[$i-2]:Compute("DNE");};
              for my$i(0..5){$ev[$i]=($L[$i]==Compute("DNE"))?$L[$i]->cmp():$L[$i]->cmp()->withPostFilter(AnswerHints(Compute("DNE")=> "Technically correct, but this question is asking for more specific information."));};
              $xmin=min(0,@a)-1;$xmax=max(@a)+1;
              @x = num_sort(
                1/(50*($a[1]-$a[0])^2)/2 + $a[0],
                -1/(50*($a[1]-$a[0])^2)/2 + $a[0],
                sqrt(abs(1/(50*($a[1]-$a[0])))) + $a[1],
                -sqrt(abs(1/(50*($a[1]-$a[0])))) + $a[1]
              );
              Context()->strings->add('does not exist'=>{alias=>'DNE'});
            </pg-code>
            <statement>
              <p>
                <m>f(x) = <var name="$f"/></m> has the graph:
              </p>
              <image>
                <latex-image>
                  \begin{tikzpicture}
                    \begin{axis}[
                      xmin = $xmin,
                      xmax = $xmax,
                      ymin = -50,
                      ymax = 50,
                    ]
                      \addplot[firstcurvestyle, -{Kite}, domain=$xmin:$x[0], samples=100] {1/((x-$a[0])*(x-$a[1])^(2))};
                      \addplot[firstcurvestyle, {Kite}-{Kite}, domain=$x[1]:$x[2], samples=100] {1/((x-$a[0])*(x-$a[1])^(2))};
                      \addplot[firstcurvestyle, {Kite}-, domain=$x[3]:$xmax, samples=100] {1/((x-$a[0])*(x-$a[1])^(2))};
                      \addplot[asymptote,-] coordinates {($a[0],-50) ($a[0],50)};
                      \addplot[asymptote,-] coordinates {($a[1],-50) ($a[1],50)};
                    \end{axis}
                  \end{tikzpicture}
                </latex-image>
              </image>
              <instruction>
                If you need to enter <m>\infty</m>, you may type <c>infinity</c>, or just <c>INF</c>.
                If the limit does not exist, you may type <c>does not exist</c>, or just <c>DNE</c>.
              </instruction>
              <!-- remaining problem code omitted for length -->
```

It produces the following TikZ code:

```
\begin{tikzpicture}
  \begin{axis}[
    xmin = -1,
    xmax = 3,
    ymin = -50,
    ymax = 50,
  ]
    \addplot[firstcurvestyle, -{Kite}, domain=-1:0.858578643762691, samples=100] {1/((x-2)*(x-1)^(2))};
    \addplot[firstcurvestyle, {Kite}-{Kite}, domain=1.14142135623731:2, samples=100] {1/((x-2)*(x-1)^(2))};
    \addplot[firstcurvestyle, {Kite}-, domain=2:3, samples=100] {1/((x-2)*(x-1)^(2))};
    \addplot[asymptote,-] coordinates {(2,-50) (2,50)};
    \addplot[asymptote,-] coordinates {(1,-50) (1,50)};
  \end{axis}
\end{tikzpicture}
```

It seems that both `x[2]` and `x[3]` are coming out equal to 2, when I would expect them to be a little less and a little more, respectively. 

Since there's division by zero when x=2, this leads to a "dimension too large" error.

By my calculations, if `a[0]=2` and `a[1]=1`, then I get `@x=num_sort(2.01,1.99,0.858578644,1.141421356)`.

After sorting, `x[0]` and `x[1]` are correct, but I should have `x[2]=1.99`, not 2, and `x[3]=2.01`, not 2.

I'm not sure why the Delta x is different for the first two than for the last two. I am going to try redoing this using the square root formula for all four points, and see if that works any better.

**Comment by Alex-Jordan** [comment]
Look in the definition of @x. There are things with ^ that should be **.
See if that fixes this.

On Thu, Jun 22, 2023 at 2:02 PM Sean Fitzpatrick ***@***.***>
wrote:

> For @Alex-Jordan
> <https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-3132feb7-454455534531-8c34945460626b92&q=1&e=c49ff541-1384-478e-83e7-b1ebb8bea1f8&u=https%3A%2F%2Fgithub.com%2FAlex-Jordan>
> but I am going to see if I can fix it myself. The following problem is in
> sec_lilmit_infty.ptx:
>
>         <exercise label="ex-limit-infinity-use-graph-2">
>           <webwork xml:id="ex-limit-infinity-use-graph-2">
>             <pg-code>
>               @a=(1..9)[NchooseK(9,2)];
>               $f=Formula("1/((x-$a[0])(x-$a[1])^(2))")->reduce;
>               $L[0]=($f->eval(x=>$a[0]-0.1)>0)?Compute("inf"):Compute("-inf");
>               $L[1]=($f->eval(x=>$a[0]+0.1)>0)?Compute("inf"):Compute("-inf");
>               $L[3]=($f->eval(x=>$a[1]-0.1)>0)?Compute("inf"):Compute("-inf");
>               $L[4]=($f->eval(x=>$a[1]+0.1)>0)?Compute("inf"):Compute("-inf");
>               for my$i(2,5){$L[$i]=($L[$i-2]==$L[$i-1])?$L[$i-2]:Compute("DNE");};
>               for my$i(0..5){$ev[$i]=($L[$i]==Compute("DNE"))?$L[$i]->cmp():$L[$i]->cmp()->withPostFilter(AnswerHints(Compute("DNE")=> "Technically correct, but this question is asking for more specific information."));};
>               ***@***.******@***.***)+1;
>               @x = num_sort(
>                 1/(50*($a[1]-$a[0])^2)/2 + $a[0],
>                 -1/(50*($a[1]-$a[0])^2)/2 + $a[0],
>                 sqrt(abs(1/(50*($a[1]-$a[0])))) + $a[1],
>                 -sqrt(abs(1/(50*($a[1]-$a[0])))) + $a[1]
>               );
>               Context()->strings->add('does not exist'=>{alias=>'DNE'});
>             </pg-code>
>             <statement>
>               <p>
>                 <m>f(x) = <var name="$f"/></m> has the graph:
>               </p>
>               <image>
>                 <latex-image>
>                   \begin{tikzpicture}
>                     \begin{axis}[
>                       xmin = $xmin,
>                       xmax = $xmax,
>                       ymin = -50,
>                       ymax = 50,
>                     ]
>                       \addplot[firstcurvestyle, -{Kite}, domain=$xmin:$x[0], samples=100] {1/((x-$a[0])*(x-$a[1])^(2))};
>                       \addplot[firstcurvestyle, {Kite}-{Kite}, domain=$x[1]:$x[2], samples=100] {1/((x-$a[0])*(x-$a[1])^(2))};
>                       \addplot[firstcurvestyle, {Kite}-, domain=$x[3]:$xmax, samples=100] {1/((x-$a[0])*(x-$a[1])^(2))};
>                       \addplot[asymptote,-] coordinates {($a[0],-50) ($a[0],50)};
>                       \addplot[asymptote,-] coordinates {($a[1],-50) ($a[1],50)};
>                     \end{axis}
>                   \end{tikzpicture}
>                 </latex-image>
>               </image>
>               <instruction>
>                 If you need to enter <m>\infty</m>, you may type <c>infinity</c>, or just <c>INF</c>.
>                 If the limit does not exist, you may type <c>does not exist</c>, or just <c>DNE</c>.
>               </instruction>
>               
>
> It produces the following TikZ code:
>
> \begin{tikzpicture}
>   \begin{axis}[
>     xmin = -1,
>     xmax = 3,
>     ymin = -50,
>     ymax = 50,
>   ]
>     \addplot[firstcurvestyle, -{Kite}, domain=-1:0.858578643762691, samples=100] {1/((x-2)*(x-1)^(2))};
>     \addplot[firstcurvestyle, {Kite}-{Kite}, domain=1.14142135623731:2, samples=100] {1/((x-2)*(x-1)^(2))};
>     \addplot[firstcurvestyle, {Kite}-, domain=2:3, samples=100] {1/((x-2)*(x-1)^(2))};
>     \addplot[asymptote,-] coordinates {(2,-50) (2,50)};
>     \addplot[asymptote,-] coordinates {(1,-50) (1,50)};
>   \end{axis}
> \end{tikzpicture}
>
> It seems that both x[2] and x[3] are coming out equal to 2, when I would
> expect them to be a little less and a little more, respectively.
>
> Since there's division by zero when x=2, this leads to a "dimension too
> large" error.
>
> By my calculations, if a[0]=2 and a[1]=1, then I get
> @x=num_sort(2.01,1.99,0.858578644,1.141421356).
>
> After sorting, x[0] and x[1] are correct, but I should have x[2]=1.99,
> not 2, and x[3]=2.01, not 2.
>
> I'm not sure why the Delta x is different for the first two than for the
> last two. I am going to try redoing this using the square root formula for
> all four points, and see if that works any better.
>
> —
> Reply to this email directly, view it on GitHub
> <https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-3132feb7-454455534531-0cacb29499c66843&q=1&e=c49ff541-1384-478e-83e7-b1ebb8bea1f8&u=https%3A%2F%2Fgithub.com%2FAPEXCalculus%2FAPEXCalculusPTX%2Fissues%2F248>,
> or unsubscribe
> <https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-3132feb7-454455534531-c4d7a023fc798101&q=1&e=c49ff541-1384-478e-83e7-b1ebb8bea1f8&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABEDOAB3PI7PUE5BKNUGFMTXMSXHTANCNFSM6AAAAAAZQXWLOI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by sean-fitzpatrick** [comment]
Yes, that's what was needed.

**Comment by sean-fitzpatrick** [comment]
Leaving this open until I get around to making the change on a different branch.

**Comment by sean-fitzpatrick** [comment]
Done.
