### ISSUE TITLE
Some global housekeeping tasks

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#25]
A few things have come up in the last few pull requests that can/should be fixed globally:
- terms with math (see #23)
- idx tags covering multiple lines (see #21)
- resizing dynamic graphs (#16)
- hyphen versus ndash
- spelling of l'hospital

These should all be easy to handle with a bit of global find/replace (hand editing needed for the first one).
I need to do a build of Chapter 5 to double check my work there. But if someone has time to look it over, we should merge #20 this week, and then I'll do a round of editing.

This should get us to a working Calculus 1.

**Comment by davidfarmer** [comment]
Additional global issues:
- Punctuation after (and occasionally before) display math
- Using `\,` before the `dx` (and not backslash-space and not nothing) (this will eventually be irrelevant when we have semantic math markup.  DF already has code to automate this.)

**Comment by davidfarmer** [comment]
Consistency of `th` (and `st`,  `nd`, and `rd`) as exponents vs inline.
(I think inline was chosen as "official" in the online discussion, but we can
have that discussion again in the context of this book.)

**Comment by davidfarmer** [comment]
Size of the partition should be a macro so that `\lVert` and `\rVert` are not hard-coded in
the source.

**Comment by davidfarmer** [comment]
Always put a 0 before the decimal point for a decimal number between -1 and 1.

**Comment by davidfarmer** [comment]
Consistent usage of `\fp` and `f'`.  See for example lines 174 and 175 of sec_deriv_inverse_function.ptx .  Let's discuss this before making any changes,
because there may be some issues that not everyone is aware of.

Later we should turn (most of) this issue into a checklist for authors/publishers who are
proofreading their work, to be posted on ptx-announce and put into the guide.

**Comment by sean-fitzpatrick** [comment]
I'll look these over. We have a `\norm` macro for `\lVert` and `\rVert`.
This wasn't used by Greg in the original LaTeX though, so some will have snuck through.

I did notice that in some cases the third derivative is set as `\fp''` and in other places as `\fpp'`.
We should try to make that consistent. Not sure which is better though.

**Comment by sean-fitzpatrick** [comment]
We also need to make a design decision on exercises with images. Right now we have a lot of exercises in Chapters 3 and 5 that are encoded as WeBWorK problems, but they also include one or more TikZ graphs. (There's some discussion on the forum between @Alex-Jordan and I.)

Eventually TikZ in WeBWorK might be a thing. But it isn't now.
We can either:
(a) remove/comment out the lines that make these into WW problems, and keep the TikZ graphs.
(b) comment out the TikZ graphs and replace them by pg graphs.

The pg graphs generated by WeBWorK do not look nearly as nice as TikZ graphs, and it would be extra work to create them.
But keeping TikZ means these become static problems, and it certainly would be nice if everything was a WeBWorK problem.

I'd like to get an opinion from @APEXCalculus on this.

**Comment by sean-fitzpatrick** [comment]
Another thing to watch out for, because it causes some serious display errors:
During the last conversion, the `\lz` (Leibniz) macro was introduced for derivatives in Leibniz notation. But it's not always implemented correctly.

See for example the section on implicit differentiation. Things are entered in the wrong place, and we get output like:
$$\frac{d}{dx^{1/2}}(=)\frac12x^{-1/2}$$

**Comment by sean-fitzpatrick** [comment]
I am wondering if perhaps one size does not fit all for WeBWorK graphs.
Right now, almost all graphs are defined with size 400 x 400.
Many are loaded without width attribute. See, for example, problems 5-12 [in the section on one-sided limits](http://www.cs.uleth.ca/~fitzpat/apex-test/sec_limits_one_sided.html)

So these are being scaled to 600 x 600. Probably too big. But maybe 47% width is too small if students are being asked to extract numerical information (like limit values) from the graph.
You can click on a graph, but the pop-out image doesn't get any bigger.
Maybe 400 x 400 was reasonable, and we just need a width="67%" to match it.

**Comment by sean-fitzpatrick** [comment]
One other global task: we need to strip `seed="1"` from WeBWorK tags.
For pages with many graphs, like the one linked above, we run into the bug observed in Portland, where each new graph replaces the ones before it.

**Comment by sean-fitzpatrick** [comment]
Looks like WeBWorK images will need to be wrapped in a sidebyside.
(Or the mbx script needs tweaking.) Explanation to follow on pretext-dev

**Comment by sean-fitzpatrick** [comment]
Done tonight:
- <idx> entries all on one line
- no more math between `<term>` tags, with an adjustment for continuity as per discussion in #23.
- fixed use of \mathcal{S} without math mode
- added 0 in front of decimals that needed it.
- updated spelling of L'Hospital

Next up: ndash and WeBWorK images.

**Comment by sean-fitzpatrick** [comment]
I didn't manage to find many instances of punctuation problems with display math.
I expect I was looking for things like
```
<me>
  (some math).
</me>
```
instead of
```
<me>
  (some math)
</me>.
```

I'll watch for it though. If you saw specific examples, let me know. It could be my search terms for this weren't quite right.

**Comment by sean-fitzpatrick** [comment]
Fixed use of `\ dx` instead of `\, dx`. (Plus all other iterations, like ds, dS, dm, d\theta, etc.)
Can't guarantee that I didn't miss some cases where there is nothing in front of the differential.
But there shouldn't be many. Greg's LaTeX was generally pretty good about this.

**Comment by sean-fitzpatrick** [comment]
I think the only things left are usage of `<ndash/>` and the `f'` vs `\fp` issue.
The former will require some care.
I didn't tackle the latter because:
- the `\fp` macro is defined as `f'` so the issue is nearly moot, except for questions of semantics and the ability to redefine the macro if needed.
- aside from a few cases (e.g. in inverse derivatives) most instances of `f'` occur in either WeBWorK problems or TikZ code. Most of these can probably be replaced without consequence but maybe not all.

**Comment by sean-fitzpatrick** [comment]
I **think** most of these have been dealt with. Going to go `<ndash/>` hunting now

**Comment by sean-fitzpatrick** [comment]
I am pretty confident that everything in this issue has been dealt with.

Further formatting problems can go into a new issue.
