### ISSUE TITLE
Exercise organization

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#257]
This is a  meta-issue to remind us of a few tasks that need to be done with exercises, and gather any relevant discussion.

1. Attempt to use two-colum layout throughout. (This was begun in #232, but that only took care of 3-column exercise groups. It didn't address exercise groups without columns, or exercises that are not in exercise groups.) Right now we do not use two colums for the Terms and Concepts, but that could be changed. Harder will be the exercises that are not part of an exercise group. Most of these tend to be problems near the end that are more involved. @APEXCalculus is it OK if these run across the whole page?
2. Track down cases of exercises with parts authored as an `ol` instead of using `task` and update them.
3. Tackle review exercises (this is already mentioned in #238)
4. This one is a question for @Alex-Jordan -- right now the "Terms and Concepts" problems are all authored (by you) as WeBWorK problems. I think if we were just starting now, we would use the interactive question types inherited from Runestone. Do you agree, or would you still prefer WeBWorK? Is it worth the effort to make the change?

**Comment by APEXCalculus** [comment]
#1: Yes, I think this is ok. I looked back at another pdf and this format look fine. It definitely helps delineate when there are problems that are not part of the exercise group that follow a group directly. In the current print version one can't immediately tell when a group ends and stand-alone problems begin.

**Comment by sean-fitzpatrick** [comment]
By 'current print version' do you mean the one produced via PreTeXt? And do you mean in the exercises section, or the answers in the back?

Here's a sample section from one of the PDFs I produced last summer:

![Screenshot from 2023-07-19 14-02-17](https://github.com/APEXCalculus/APEXCalculusPTX/assets/16246721/587f5175-be08-43a0-933d-69b362df461e)

It seems all right to me?

**Comment by sean-fitzpatrick** [comment]
Here's what the corresponding answers in the back look like:

![Screenshot from 2023-07-19 14-06-09](https://github.com/APEXCalculus/APEXCalculusPTX/assets/16246721/1d0627e2-971c-4504-974a-a7f90774aa90)

**Comment by APEXCalculus** [comment]
"Current print version" is the version one can buy from Amazon, using the original always-in-2-column-mode format. That format can be confusing when moving from exercise set to standalone problems.

The screenshot you posted first is what I was looking at when I thought it looked ok.

Your second screenshot also seems fine, though I am reminded of my impression that the word "Answer" is unnecessary and excessive. I also find the numbering potentially confusing. In Section 6.4, the problems are just numbered 1, 2, etc. In the Answer section, they are numbered 6.4.1, 6.4.2, etc. I don't think that's necessary. Further, in one of the pdf's you sent earlier, in some sections each problem is identified with 4 numbers (such as 6.1.5.1, for Chapter 6, Section 1, SubSection 5, problem 1). 

I'll make a separate issue for this so the issue can be dealt with separately.

**Comment by sean-fitzpatrick** [comment]
That numbering problem I think should be fixed for future versions. There was a setting that was incorrect in the publisher file. 

My local versions are divided into parts for the different semesters of calclulus. So the relevant "level" setting was 3 for what should be used, and displayed in the TOC: Part/Chapter/Section.

But level 3 for the official versions, which don't have parts, leads to Chapter/Section/Subsection. I corrected this to set the level to 2, so that subsections are left out.

I will look into whether we can hide "answer" in the back.

**Comment by APEXCalculus** [comment]
If hiding the Answer in the back is too hard via PreTeXt, it won't be hard to do on the LaTeX side. There's already going to be some post-processing, I'm sure, and that issue won't be hard to address. The key is if someone really thinks that word needs to be there. It seems redundant to me.

**Comment by Alex-Jordan** [comment]
Three are situations where "Answer" or something like that is nicer than
not having it, and it's maybe just not coming up with APEX as it is now.
Like what if these problems also had walkthrough solutions. Then it would
be like:

Answer:  5
Solution: You start with 2 and then you add the 3 and you get 5.

The other situation is one question with multiple answer blanks, where
"Answer 1", "Answer 2" etc makes things unambiguous. But it can seem a bit
much, and I know Sean is working to move to tasks in a way that will make
that happen less.

You could try using "rename" to rename "answer" to the empty string? Not
sure if that will fly. And you'd want to do it in some way that only
applied for print, since you need "Answer" as the clickable in HTML.

On Wed, Jul 19, 2023 at 1:45 PM Gregory Hartman ***@***.***>
wrote:

> If hiding the Answer in the back is too hard via PreTeXt, it won't be hard
> to do on the LaTeX side. There's already going to be some post-processing,
> I'm sure, and that issue won't be hard to address. The key is if someone
> really thinks that word needs to be there. It seems redundant to me.
>
> —
> Reply to this email directly, view it on GitHub
> <https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-3132feb7-454455534531-9b485b961db516e2&q=1&e=07c8c806-2daa-498a-a6de-57241879a035&u=https%3A%2F%2Fgithub.com%2FAPEXCalculus%2FAPEXCalculusPTX%2Fissues%2F257%23issuecomment-1642730998>,
> or unsubscribe
> <https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-3132feb7-454455534531-f57cb8b19b3321ef&q=1&e=07c8c806-2daa-498a-a6de-57241879a035&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABEDOAA5VHYPA25JSSJHY43XRBBNDANCNFSM6AAAAAA2QJ2MYE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by Alex-Jordan** [comment]
Can you use component on rename? And print flavors are the only versions that use the rename? If it works, it sounds simplr than more extra XSL. But maybe you have something good in mind.

**Comment by sean-fitzpatrick** [comment]
I have an experiment I want to try, but I can't get the new CLI version to generate WeBWorK.

I'll try doing it manually once kids are in bed

**Comment by sean-fitzpatrick** [comment]
I don't think my idea will work,but maybe there's a way to use it.
My thought was that in the `en-US.xml` localization file, there's an entry for `answer`, which is currently "Answer".
If this was the empty string, we'd get what we want. But I don't know if there's a way to override a locale.

**Comment by APEXCalculus** [comment]
I get the Answer/Solution response. I also see why the word Answer is useful for the HTML.
In the current case of APEX, it seems like a disproportionate amount of blank ink on each page is used on the word Answer. If there's a way to turn that into an empty string, I think that would be great. Post processing the .tex file at the end seems to be another viable option if that is too hard to do.

**Comment by sean-fitzpatrick** [comment]
Good news and bad news. The good news is that the PreTeXt code appears to be smart enough that if you are only printing answers and not solutions, it leaves out the 'Answer' part.

The bad news is that numbering is wonky: the numbering varies, depending on whether or not a section has subsections. I've posted on pretext-support to see if there's a way to fix this.

**Comment by sean-fitzpatrick** [comment]
Points 1 and 2 in this issue are now taken care of. I might try to take on point 3 soon.
@Alex-Jordan that leaves point 4, on which I need your opinion: would it be better to write the terms and concepts problems using the interactive formats we inherited from Runestone?
(Maybe this is too much work to get done this summer in any case.)

**Comment by sean-fitzpatrick** [comment]
I'm going to close this. I think I've dealt with everything but the review exercises, and there's a separate issue for that.

Moving review exercises to a chapter review would be great! But I don't think I have the time to tackle it now.
