### ISSUE TITLE
Organization of one exercise group

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#259]
For @APEXCalculus .

This [exercise group](https://opentext.uleth.ca/apex-calculus/sec_cylindrical_spherical.html#exercisegroup-352) in the cylindrical and spherical coordinates section has awkward organization.

Each question gives two sets of bounds in cylindrical coordinates, followed by two sets in spherical. This ends up looking like:

Bounds in cylindrical coordinates:
(a)
(b)

Bounds in spherical coordinates:
(a)
(b)

I would like to change this to two exercise sets: one for cylindrical, and one for spherical. Each of these exercises would then be split into two exercises, each with two parts. Does this seem reasonable?

**Comment by APEXCalculus** [comment]
Yes, your suggestion seems better than what I did. I don't recall my rationale for that setup.

**Comment by sean-fitzpatrick** [comment]
OK, I'll proceed with changes soon. This makes it easier to organize things by `task`.

**Comment by sean-fitzpatrick** [comment]
Fixing this is included in #260.
