### ISSUE TITLE
Too much whitespace after some images

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#26]
See for example the first two figures in the section on derivatives of inverse functions:
[http://www.cs.uleth.ca/~fitzpat/apex-test/sec_deriv_inverse_function.html](http://www.cs.uleth.ca/~fitzpat/apex-test/sec_deriv_inverse_function.html)

I don't see this in the old build of the book on the PCC website, but the image code is unchanged between versions -- I think the only change made was to remove the CDATA wrapper.

So I'm not sure what is causing the whitespace when I build the book, but not previously.
One possible problem on my end: I'm using Inkscape as a replacement for pdf2svg, since the latter is not installable on my office computer. You'll notice that some labels that have square roots in them (like further down in this section) are not rendered properly.

**Comment by davidfarmer** [comment]
The whitespace is due to the image not being cropped.  You can see
this by clicking on the image to make it big.

**Comment by sean-fitzpatrick** [comment]
Makes sense. I might need to start building on my WeBWorK server, or find an old laptop.
Some of the helper functions for mbx are either out of date, or not even installable on my office workstation. But I thought my only problem was pdf to svg conversion -- cropping seemed mostly OK.

If cropping works properly for others we can close this.

**Comment by sean-fitzpatrick** [comment]
Surely this is resolved. I haven't noticed whitespace issues lately. Reopen if I'm wrong.
