### ISSUE TITLE
WeBWorK problem sometimes fails to build

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#270]
Wondering if @Alex-Jordan can spot anything wrong here.

Somewhat inconsistently, the following WeBWorK problem will throw an error.
I would like to provide a better error report (e.g. by running with debug to get the PG code and see if it fails) but everytime I rerun with `-v debug` everything works fine. So I don't understand why this sometimes fails, especially since we always use the same seed if no change has been made to the build target.

Here's the code:

```
          <webwork xml:id="ex-deriv-intro-approx-2">
            <pg-code>
              $b=non_zero_random(-10,10,1);
              $c=non_zero_random(-9,9,1);
              $a=non_zero_random(-9,9,1);
              if($envir{problemSeed}==1){$a=10;$b=1;$c=9;};
              Context("ImplicitPlane");
              Context()->variables->are(x=>'Real',y=>'Real');
              $f=Formula("$b/(x+$c)")->reduce;
              $fa=$f->eval(x=>$a);
              $h=0.1;
              $m=($f->eval(x=>$a+$h) - $fa)/$h;
              $tangentline=Compute("y=$m(x-$a)+$fa");
            </pg-code>
            <statement>
              <p>
                <m>f(x) = <var name="$f"/></m> and <m>a=<var name="$a"/></m>
              </p>
              <p>
                <var name="$tangentline" width="20"/>
              </p>
            </statement>
          </webwork>
```

It looks like there's potential for division by zero in the definition of `$f`. But I changed the third line to
`do {$a=non_zero_random(-9,9,1)} until ($a+$c != 0);` and I still got an error on the next run, so maybe there's something else that's off? The code looks perfectly fine to me.

Could be a sever glitch, but why always on this problem?

**Comment by Alex-Jordan** [comment]
If it's the same seed, everything should be the same on different runs. Can you providee any more information about *how* it fails when it fails?

Probably unrelated observations:
* I think you can remove `if($envir{problemSeed}==1){$a=10;$b=1;$c=9;};`. That was from back when we declared `@seed="1"` in the `webwork`.
* Perhaps change the initialization of `$a,$b,$c` to: `($a,$b,$c) = random_pairwise_coprime([-9..-1,1..9], [-10..-1,1..10], [-9..-1,1..9]);`

**Comment by sean-fitzpatrick** [comment]
The trouble is that the message for any WeBWorK failure is now the same, that the problem is missing a statement tag.

This really just means that the WeBWorK problem threw an error. When I try to investigate by running with debug turned on, the damn thing works so I'm unable to learn what went wrong.

**Comment by Alex-Jordan** [comment]
Can you minimize things so this is the only exercise it tries to build, and then get the issue to happen consistently?

Are you only working with CLI? If not, even without the debug flag, you could hack the pretext script to print whatever it is declaring it gets back.

Have you continued updating the main branch of webwork2 and pg?

**Comment by sean-fitzpatrick** [comment]
I do need to update the WeBWorK server.

I'm using the CLI, and I can't reproduce this consistently. The last time I ran a build without debugging on, it failed.

I've done a dozen builds since then with debugging on, and it's worked every time.

**Comment by sean-fitzpatrick** [comment]
I haven't run into this issue while building in quite some time, so I'm closing this issue.
