### ISSUE TITLE
Problem with WW TikZ graphs in Section 1.1

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#279]
There is a cropping issue that I reported on pretext-dev, but I have also noticed a problem with how the solid and hollow dots are plotted in these problems.

@Alex-Jordan when you have time, can you take a look? The images are visible (for now) at [this build of APEX](https://opentext.uleth.ca/image-test/sec_limit_intro.html#exset-limit-intro-numerical-graphical) we were using for image description work.

They are images in the solutions, so in other versions they may not be present, and if they are, you'll have to go hunting in the back matter.

The issue is that although the two halves of a piecewise-defined function are plotted using domains that should overlap at the point where the function changes from one formula to another, the circles used to indicate if a point is included or not are slightly offset, as if the domain was something like `-2:$a-0.1` for one half, and `$a+0.1:2` for the other half.

[This graph](https://opentext.uleth.ca/image-test/sec_limit_intro.html#ex-limit-intro-numerical-graphical-11) in particular does not look good. The two halves of the graph should meet at a single open circle.

**Comment by sean-fitzpatrick** [comment]
Actually, that one I think I know how to fix: the function is not defined at 0, so the domain *is* offset for that function. But for others it isn't, and I see similar issues. For that graph I think I need to remove the `infiniteopen` and `openinfinite` styles, and manually plot a single dot.

**Comment by Alex-Jordan** [comment]
If the previous example is not a representative example, can you provide a link to one to take a closer look at? Also to some source where I could investigate the potential PG issue independent from PreTeXt.

**Comment by sean-fitzpatrick** [comment]
Here is a better example:
Exercise 16 
https://opentext.uleth.ca/image-test/sec_limit_intro.html#ex-limit-intro-numerical-graphical-10

On phone, so I'll grab the code in a separate comment

**Comment by sean-fitzpatrick** [comment]
The code for that problem begins here:
https://github.com/APEXCalculus/APEXCalculusPTX/blob/main/ptx%2Fsec_limit_intro.ptx#L2232

**Comment by sean-fitzpatrick** [comment]
Here's another example, but this one is not WeBWorK-generated:
https://opentext.uleth.ca/image-test/sec_extreme_values.html#fig_extreme

The code for the first image:
```
<latex-image>

\begin{tikzpicture}
\begin{axis}[ ymin=-.9,ymax=5.5,xmin=-2.2,xmax=2.2,]
\addplot+[domain=-2:2,-] {-x^2+5};
\addplot[hollowdot] coordinates {(-2,1) (2,1)};
\addplot[openinterval] coordinates {(-2,0) (2,0)};
\end{axis}
\end{tikzpicture}

</latex-image>
```
Notice how the `openinterval` along the x axis doesn't quite reach the endpoints at -2 and 2.

I would expect that the open circles at the ends of the graph align vertically with the ends of the interval beneath it, but they extend further than the interval.

The styling for this is set in the `docinfo` as follows:
```
\pgfplotsset{openinterval/.style={color=black,mark=none,ultra thick,{Circle[open]}-{Circle[open]}}}
```
So I think the issue is with the pgfplots `Circle` command used throughout `docinfo`. I don't think it centres the circle at the given coordinate.

**Comment by sean-fitzpatrick** [comment]
I'm going to close this, since it's a server software issue and not a ptx source issue. I will apply the fix suggested by @Alex-Jordan on pretext-dev and next month I'm planning to move our servers to Ubuntu 24.04, which should get us TL 2024.
