### ISSUE TITLE
Exercises with required information in the graph

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#280]
Consider this [exercise set](https://opentext.uleth.ca/image-test/sec_extreme_values.html#exset-graph-extreme-values-evaluate-fprime) in Section 3.1.

For each exercise, the reader is asked to evaluate a derivative at a point indicated on the graph.

I'm hoping to send a pull request soon that will add both short and long image descriptions for these exercises.
That's better than what we have now, but is it enough?

Or should we also re-write these questions so that the required points are indicated in the question text as well?

**Comment by sean-fitzpatrick** [comment]
@APEXCalculus we now have image descriptions for these exercises, but I've just noticed that the "long" description doesn't appear in WeBWorK exercises. This might be something @Alex-Jordan has fixed (or will fix) in a newer WeBWorK version.

But I think we should change the instruction ("Evaluate f' at the points given in the image") to "Evaluate f' at the given point(s)", and then include each point in the question text.

However I still have one question: do we simply give the point, or do we also describe it? (E.g., do we say, "at the point (2,1)", or "at the point (2,1), where there is a cusp/horizontal tangent"?)

**Comment by APEXCalculus** [comment]
How detailed are the short image descriptions? In the description, could we
say "the point (2,1) where there is a cusp", but leave that part out of the
exercise statement? Or does that make a "short" description too long?

I'm fine with listing the points in the statement. I think adding the extra
description to the statement makes things wordy, but it isn't the worst.
I'm ok with it if that's what needs to be done.

**Comment by sean-fitzpatrick** [comment]
Right now the short descriptions are along the lines of "Graph of a sine wave from 0 to 2 pi. The marked points are (pi/2, 1) and (3 pi/2,-1)". Not great, but workable. We are probably OK here.

[Problems 7 and 8](https://opentext.uleth.ca/apex-standard/sec_extreme_values.html#exset-graph-extreme-values-identify-points) are currently impossible for someone who can't see the image well. But I don't think there's anything we can do about that until capability for long descriptions is added to WeBWorK.

A student who can't see those graphs would just have to be allowed to opt out of those problems.

**Comment by APEXCalculus** [comment]
In those cases, the only thing I'd think to do was make the short
description longer. I have no idea if there's a limit to the length of the
short description.
For the visually impaired, audible assistance will be needed to read the
problem and the short/long descriptions. As this is the case, I'd keep the
info that can't be seen in the description portion to keep the regular
problem statement as brief/uncluttered as possible.

**Comment by sean-fitzpatrick** [comment]
I think we live with this for now, and hopefully a future version of webwork will incorporate the descriptions that we've written.
