### ISSUE TITLE
Accessibility of scatter plots in series section

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#292]
Question for @Alex-Jordan .

In [this example](https://opentext.uleth.ca/apex-standard/sec_series.html#ex_series1), scatter plots are shown for both the terms in a sequence, and the corresponding partial sums.

The only thing differentiating the two sequences being plotted is the colour: the sequence is in blue, and the partial sums are in red. I think this could be an issue for some colour-blind readers. But we are plotting points, so we can't rely on line style.

The second plot is more problematic, since it shows the sequence and the partial sum coinciding for every second term. Right now we see this as the red dot inside the blue dot, so there is a thin blue border around the red dot.

I'm adding a text decription, which will help, but is there any other improvement we could make?

**Comment by APEXCalculus** [comment]
What if we used shapes in addition to colors? (colours) For instance, red
circles and blue squares? Something like this:
[image: image.png]

**Comment by sean-fitzpatrick** [comment]
The image didn't show up, but I know what you mean. I think that would help.

**Comment by APEXCalculus** [comment]
![image](https://github.com/APEXCalculus/APEXCalculusPTX/assets/6805271/a8d690a9-7639-4ff2-bfbe-896fa9e99e95)

**Comment by sean-fitzpatrick** [comment]
Addressed in #298
