### ISSUE TITLE
Little things, mostly punctuation

### ISSUE THREAD

**Issue by davidfarmer** [APEXCalculus/APEXCalculusPTX#30]
This issue is to collect little things that are easy to fix.

3rd formula after Figure 4.5.1, sentence starting "Let's start with...":  no period at end of sentence.

Formula immediately before Figure 4.5.4:  The "(x)" is on the wrong side of the equals.

Solution to Example 4.5.13.:  no period after first display.  Also at the end of sentence
starting  "Since we are forming..."

Solution to Example 4.5.18.:  Two missing periods at end of sentences (that end in a display).

**Comment by sean-fitzpatrick** [comment]
Fixed. This section usually comes later (Chapter 8). I pulled it in since this is where I'll put it for the Lethbridge version of the book. So I don't think it had seen much hand editing yet. Thanks for the catches.

**Comment by sean-fitzpatrick** [comment]
See the list of 'important points' immediately after Theorem 5.1.6.
It's marked up as a `<ul>` with each `<li>` containing a `<p>` containing an `<me>`.
So the math is centred, with a big gap between the bullet point and the equation.

Probably we should use `<m>\displaystyle ...</m>` here?
It's in use elsewhere. If we're consistent it'll be easier to update if there's progress on the issue regarding lists of equations that came up previously.

**Comment by sean-fitzpatrick** [comment]
In that same list: the discussion on needing `<m>n\neq -1</m>` in the power rule has an unfortunate line break in the equation (on my screen, at least). Maybe put this in display math?

**Comment by sean-fitzpatrick** [comment]
Question 6 in 5.1 doesn't work. I think this is one of several that tries (unsuccessfully) to use <fillin/> in a WeBWorK problem.

**Comment by sean-fitzpatrick** [comment]
I suspect @davidfarmer will have something to say about the comma in Section 5.2 at the end of the 'text equation' `distance = rate_1\times time_1 + rate_2\times time_2`.

(It's done in math mode with \text. There's another one I tried marking up using `<times/>` and regular text. But here the subscripts stumped me.)

**Comment by sean-fitzpatrick** [comment]
Some graphs look wrong in Chapter 5 and later, due to an oversight on my part.
We added some additional global styling definitions in the index.ptx file, and used them to update graphs. This was done on apex-mbx and then merged in, but I forgot to do the index file.

It'll get fixed in the next pull request.

**Comment by sean-fitzpatrick** [comment]
@davidfarmer I'm pretty sure everything here was dealt with long ago. Closing.
