### ISSUE TITLE
Asymptote background

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#302]
Just a caution: I added a setting to the asymptote preamble that produces better results for the HMTL version.
But it is **not** good for PDF: the transparent background becomes black in the PDF version.

I will see if I can come up with a solution that is better than adding further clutter to the `docinfo`.

(One option: right now we use two "components", one for colour, and one for black and white, with different colour settings, for both TikZ and Asymptote. I could move to using three compoents: HTML, colour print, and BW print. But that will add a third copy of the `asymptote-preamable` and require an additional publisher file.

**Comment by sean-fitzpatrick** [comment]
Of course John Bowman knew how to fix it:

`currentlight.background=opacity(settings.outformat == "html" ? 0.0 : 1.0);`

I'll make this change the next time I have enough for a pull request.

**Comment by APEXCalculus** [comment]
Of course he did.
Somehow I'm often surprised at the usage of Asymptote syntax. I tend to
forget it's a programming language and one can build switches/if-then
statements right inside.

**Comment by sean-fitzpatrick** [comment]
That said, when I try this it does not seem to work. I still get a dark background for PDF output with this line added.

If I remove it completely, I get white background.

**Comment by sean-fitzpatrick** [comment]
This seems to work: `if(settings.outformat == "html") currentlight.background=opacity(0.0);`

I'll test a bit more...

**Comment by sean-fitzpatrick** [comment]
This is settled with #303
