### ISSUE TITLE
Diagrams for related rates exercises

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#31]
The exercises in the related rates section were all coded as WeBWorK problems -- good.
Many of them in the original LaTeX had diagrams, either from tikz source or an external image file. These aren't making it into the WW problems -- not so good.

Here I don't think a pg-graph can help, since they're things like an airplane flying over an anti-aircraft gun.

So either these have to become static exercises, or we need to include externally generated image files.

**Comment by sean-fitzpatrick** [comment]
There are a couple of problems in the optimization section with the same issue.
(And maybe a couple more that should have a diagram included but don't.)

**Comment by sean-fitzpatrick** [comment]
And the last group of problems on differentials.

**Comment by sean-fitzpatrick** [comment]
@Alex-Jordan should these problems perhaps be prioritized for PG-TikZ code?

**Comment by Alex-Jordan** [comment]
Maybe! The unfortunate truth is I can't get back to that in time for Fall though. Any luck on finding a student willing to take it on?

**Comment by sean-fitzpatrick** [comment]
Even if I could find one, cuts to the universities here mean there's no money to pay them.
I don't think many of these are randomized and there aren't that many overall. I'll see what iI can figure out today.

**Comment by sean-fitzpatrick** [comment]
This might finally get dealt with this summer: I'll bring the WeBWorK server running APEX up to 2.17, and then we can have TikZ in WeBWorK.
@Alex-Jordan I might have to get you to remind me exactly what is changing in 2.17 and how that effects the way we write TikZ into a PreTeXt-WW problem.

**Comment by sean-fitzpatrick** [comment]
This was dealt with some time ago. All these images are now done in TikZ.
