### ISSUE TITLE
Domain issue for inverse function derivative

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#313]
I can fix this, but I need some help from @Alex-Jordan on the WeBWorK syntax.

[This exercise](https://opentext.uleth.ca/apex-standard/sec_deriv_inverse_function.html#ex-deriv-inverse-evaluate-2) gives a point (-6,51), and then says that it's on the graph of a parabola where x is greater than or equal to 1.

I'd like to fix the domain to avoid the contradiction. Right now the problem is programmed as follows:
```
        <exercise label="ex-deriv-inverse-evaluate-2">
          <webwork xml:id="webwork-ex-deriv-inverse-evaluate-2">
            <pg-code>
              Context("Fraction");
              ($h,$c,$x0) = (-9..-1,1..9)[NchooseK(18,3)];
              if($envir{problemSeed}==1){$h=1; $c=4; $x0=3;};
              $f = Formula("x^2 - 2*$a x + $c")-&gt;reduce;
              $y0 = $f-&gt;eval(x=&gt;$x0);
              $point = Point($x0,$y0);
              $fp = $f-&gt;D('x');
              $fpx0 = $fp-&gt;eval(x=&gt;$x0);
              $fipy0 = Fraction(1/$fpx0);
            </pg-code>
            <statement>
              <p>
                The point <m><var name="$point"/></m> is on the graph of <m>f(x) = <var name="$f"/>, x\geq 1</m>.
                Find <m>\left(f^{-1}\right)'(<var name="$y0"/>)</m>.
              </p>
              <p>
                <var name="$fipy0" width="20"/>
              </p>
            </statement>
          </webwork>
        </exercise>
```
I don't really know how the `NchooseK` function works -- I suspect it might be pure Perl, because I can't find it in the WeBWorK documentation. Is it just saying to choose 3 values from those 18 choices?

If so, I think I need to replace ` ($h,$c,$x0) = (-9..-1,1..9)[NchooseK(18,3)];` with
```
 ($h,$c) = (-9..-1,1..9)[NchooseK(18,2)];
 x0 = random(1,9,1);
```
but I want to make sure I'm understanding things correctly before making the change.

**Comment by Alex-Jordan** [comment]
There's a bigger mistake here, in that `$a` is never defined. It is used in a string, so if it is interpolated as the empty string, it is not causing an error message. The way this is coded right now, the linear term of `$f` is always `-2x`. Meanwhile, `$h` is set, but never used. Maybe `$a` should be `$h`?

A possible issue with your suggestion is that you could end up with `$x0` equal to `1`, which is the x-value of the parabola's vertex. So the inverse's derivative there is undefined. Of if `$a` is replaced with `$h`, you could end up with `$x0` equal to `$h`, and have the same issue. 

I think I would leave that part of the code alone (except replace the deprecated `NchooseK` with `random_subset`) and instead make the inequality sign be conditioned on how `$x0` and `$h` relate to each other.
```
        <exercise label="ex-deriv-inverse-evaluate-2">
          <webwork xml:id="webwork-ex-deriv-inverse-evaluate-2">
            <pg-code>
              Context("Fraction")->noreduce('(-x)-y', '(-x)+y');
              ($h,$c,$x0) = random_subset(3, -9 .. -1, 1 .. 9);
              if($envir{problemSeed}==1){$h=1; $c=4; $x0=3;};
              $f = Formula("x^2 - 2*$h x + $c")->reduce;
              $y0 = $f->eval(x => $x0);
              $point = Point($x0,$y0);
              $fp = $f->D('x');
              $fpx0 = $fp->eval(x => $x0);
              $fipy0 = Fraction(1/$fpx0);
              $sign = ($x0 > $h) ? '\geq' : '\leq';
            </pg-code>
            <statement>
              <p>
                The point <m><var name="$point"/></m> is on the graph of <m>f(x) = <var name="$f"/>, x <var name="$sign"/> <var name="$h"/></m>.
                Find <m>\left(f^{-1}\right)'(<var name="$y0"/>)</m>.
              </p>
              <p>
                <var name="$fipy0" width="20"/>
              </p>
            </statement>
          </webwork>
        </exercise>
```

Or if you always want it to be `\geq`, then make sure `$x0` is greater than `$h`:

```
        <exercise label="ex-deriv-inverse-evaluate-2">
          <webwork xml:id="webwork-ex-deriv-inverse-evaluate-2">
            <pg-code>
              Context("Fraction")->noreduce('(-x)-y', '(-x)+y');
              ($h,$c,$x0) = random_subset(3, -9 .. -1, 1 .. 9);
              ($h, $x0) = num_sort($h, $x0);
              if($envir{problemSeed}==1){$h=1; $c=4; $x0=3;};
              $f = Formula("x^2 - 2*$h x + $c")->reduce;
              $y0 = $f->eval(x => $x0);
              $point = Point($x0,$y0);
              $fp = $f->D('x');
              $fpx0 = $fp->eval(x => $x0);
              $fipy0 = Fraction(1/$fpx0);
            </pg-code>
            <statement>
              <p>
                The point <m><var name="$point"/></m> is on the graph of <m>f(x) = <var name="$f"/>, x \geq <var name="$h"/></m>.
                Find <m>\left(f^{-1}\right)'(<var name="$y0"/>)</m>.
              </p>
              <p>
                <var name="$fipy0" width="20"/>
              </p>
            </statement>
          </webwork>
        </exercise>
```

**Comment by sean-fitzpatrick** [comment]
Thanks! Yes, my random should have started at 2, not 1. And I think `$h` should have been `$a`.

I like your solution to swap the inequality depending on the relative values.

**Comment by sean-fitzpatrick** [comment]
Fixedin #314, using the first option from Alex.
