### ISSUE TITLE
Cube root

### ISSUE THREAD

**Issue by Alex-Jordan** [APEXCalculus/APEXCalculusPTX#52]
Brace yourself, this will be stepping on convention :) 

How important is it for `x^(2/3)` to mean exactly the same thing as `(x^2)^(1/3)`? I follow a convention where `x^(2/3)` is undefined (as a real number) for negative `x`, but `(x^2)^(1/3)` is of course always defined for negative `x`. The convention I follow is not based in some principle of pure mathematics, but rather it is a practical issue when using a programming language or a CAS. For example, compare [this](https://www.wolframalpha.com/input/?i=%28-8%29%5E%282%2F3%29) with [this](https://www.wolframalpha.com/input/?i=%28%28-8%29%5E2%29%5E%281%2F3%29).

APEX treats `x^{2/3}` to mean exactly the same thing as `(x^2)^(1/3)` no matter what the base is. For example, [here](http://www.cs.uleth.ca/~fitzpat/apex-calculus/sec_incr_decr.html#ex_incr3).

Is there anything to do with this? For example, change `x^{2/3}` to `\abs{x}^{2/3}` or `(x^2)^{1/3}` or `\sqrt[3]{x^2}`? I realize all such changes lead to more cumbersome/tedious lines when calculating a derivative. On the other hand, when a student types the function formula into a graphing application, changes of this nature would lead to the result matching what they see graphed in their book.

Also, please forgive me if this was already discussed in an old thread and I lost it.

**Comment by sean-fitzpatrick** [comment]
I think you only get that output from Wolfram Alpha (or similar) if you don't specify the domain.

Over the real numbers, there is nothing ambiguous about cube roots of negative numbers: x^3 has a unique inverse defined for all real numbers.

This is pretty standard interpretation in calculus books (e.g. Stewart).

**Comment by sean-fitzpatrick** [comment]
Your CAS may allow for complex solutions, in which case all numbers have three complex roots, including positive real ones!

**Comment by Alex-Jordan** [comment]
> Over the real numbers, there is nothing ambiguous about cube roots of negative numbers: x^3 has a unique inverse defined for all real numbers.

The thing is that this reply signals that you have internalized `x^{1/3}` to mean `\sqrt[3]{x}`, which I know is common. But that is the point: they aren't the same. They happen to be the same on positive reals, and I think that gets internalized too far. Maybe that should just be declared to be the convention. 

Consider: if `-2 = (-8)^(1/3)`, then shouldn't `-2 = (-8)^(2/6)`? Now are we taking a 6th root of -8?  Since `1/3` is close to `333/1000`, should the result be close to `(-8)^(333/1000)`?

**Comment by Alex-Jordan** [comment]
I guess I have to accept that while `x^y` normally means something like `exp(y ln(x))` for most real `y`, in the special case where `y` is _written_ as a rational number with an odd denominator, it means something else.

It still causes confusion when the graphing and CAS devices disagree. In the old days, their TI calculator would not plot `x^(1/3)` for negative `x`. Or right now GeoGebra will plot `x^(1/5)` over all reals, but only plots `x^0.2` over positives. So something is recognizing the "form" of the exponent.

**Comment by Alex-Jordan** [comment]
I just submitted #53, which includes a WW problem with raising to the 2/3 power. I left it with domain all of R.

Here is a note about this we put in our calc I lab manual:
https://spot.pcc.edu/math/clm/appendix-useful-algebra.html

**Comment by APEXCalculus** [comment]
At the time of writing, I remember thinking through some of the issues related to rational powers. As implied by your PCC manual, it came down to adopting a convention that stays consistent across applications, acknowledging that the domain is the Reals. And then not addressing all the quirks in an introductory text as it will just confuse students. Once they get to Complex Analysis they can see a whole new perspective.

It is nice to interpret y=x^(2/3) as (x^2)^(1/3), leading to y^3 = x^2 and the parametric equations x=t^3, y=t^2.  But Alex raises a good point: is y = x^(2/3) = x^(4/6)? If so, then isn't the same curve parametrized by x=t^6, y=t^4? But this latter curve has only positive x-values ...

I *think* we can resolve this issue either by restricting everything to the positive reals (which I find too restrictive) or by adopting the convention that y = x^(m/n) is only well defined when m & n are relatively prime. This is what the text does in the Implicit Differentiation section to justify the derivative of y=x^(m/n), though we don't explain why that restriction is in place, nor what to do in the case when m & n aren't relatively prime.

*Someday* I'd like to write up a document that. I know it's been addressed before, though perhaps not in a manner/place that is easily accessible to students.

**Comment by Alex-Jordan** [comment]
Thanks both for tolerating my peevish musings.

I think the most clear example of the issue (which for me is really about using modern technology and programming, not really about pure math considerations) using 2020 technology options is how GeoGebra is plotting `x^(1/5)` differently from `x^0.2`. So I'm filing that one away, alongside WolframAlpha's `(-8)^(1/3)` (not real) versus its `cuberoot(-8)` (negative two).

Full speed ahead, and maybe someday there will be a good place to catalog this (and other APEX conventions) somewhere in the front matter.

**Comment by sean-fitzpatrick** [comment]
There's maybe room for an `<aside>` somewhere pointing out that we mean \sqrt[3]{x} when we write x^{1/3}. It would be a shame to dispense with negative values in the domain altogether, because functions involving odd roots are one of the simplest sources of critical numbers arising because the derivative is undefined. (And from there, leading to discussion of vertical tangents vs. cusps, etc.)

Most other examples in Calc I come from piecewise-defined functions (e.g. absolute value).

PS: I have to confess that I have yet to teach an introductory math course that allowed anything more advanced than a "5 function" calculator (e.g. those dollar store calculators that do basic arithmetic and nothing else). We usually don't even allow scientific calculators.

**Comment by APEXCalculus** [comment]
FWIW, Mathematica's CubeRoot function was created in 2012 in Version 9.0. That is, for many, many years it was frustratingly difficult to get Mathematica to tell you the cube root of -8 was -2, a common sense answer to many people. (I'll wager they created it to stop getting angry emails.)

While I'm a huge fanboy of Mathematica, it has quirks. See the Documentation screenshot below. If you look closely, the first surd slightly closes at the end ... not that we'd expect anyone to notice that right away.

![image](https://user-images.githubusercontent.com/6805271/82718530-0194fc00-9c71-11ea-9faf-796b302c00c1.png)
