### ISSUE TITLE
File cleanup

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#73]
Checking to see if there is any reason to keep any of the following:

- `ptxConversion0/` (this is David's conversion of APEX V3. I'm pretty sure we're done with it)
- `exercises/` (LaTeX source for exercises; also on APEXCalculusV5)
- `figures/` (LaTeX source for figures; also on APEXCalculusV5)
- two Mathematica notebook files

If nobody objects, I'll just remove these as a commit direct into `master`.

**Comment by Alex-Jordan** [comment]
It seems safe to me to knock off the first three.

What is the story with the Mathematica files? If either of them is the "source" for that one Mathematica image, I think it should be kept.

**Comment by sean-fitzpatrick** [comment]
We'll have to ask @APEXCalculus about that one. I don't have access to a Mathematica license!

**Comment by APEXCalculus** [comment]
I'm good deleting the listed files and folders.

The Mathematica files can go, too. I have copies in the V5 repo if I need
it again. (It does a ton for me - coincidentally, I used it to create the
conic section images we now want to replace. It also helped me created data
points for plotting odd functions in pgfplots, among other things.)

**Comment by sean-fitzpatrick** [comment]
I did this on my fork (where I'm working) and now I wish I hadn't, since there are some 5000 files that get deleted.
So the good news is that I can merge my fork into `master` here automatically with no conflicts.
The bad news is that anyone reviewing that pull request will see thousands of files being changed.
(When in fact it's a relatively tiny 100 files being changed.)

**Comment by sean-fitzpatrick** [comment]
This was resolved some time ago
