### ISSUE TITLE
Conic section images

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#74]
Yesterday during PreTeXt development drop-in we discussed replacing the conic section `png` images with Asymptote equivalents.

@APEXCalculus are you interested in taking that on? You're probably the most experienced with Asymptote code here.
If not, it might be a good exercise for me to figure out how to do it. (After spending months working on how to process Asymptote code, maybe I should learn to write some!)

**Comment by APEXCalculus** [comment]
Shouldn't be terrible - are you talking of the 7 images on page 497, the
intro? Yes, I'll take a stab at making them in Asymptote.

**Comment by sean-fitzpatrick** [comment]
Can't recall the page number but the ones right at the start of the [section on conic sections](http://www.cs.uleth.ca/~fitzpat/apex-calculus/sec_conic_sections.html). (And yes, seven of them.)

Other than a Mathematica plot, these are the only figures left that are not generated from source.

**Comment by APEXCalculus** [comment]
I started working on the Asymptote versions of the conic sections. To be
honest, so far am not thrilled with the outcome. For starters, it took a
while to get Asymptote updated & running on my machine. Still can't get
good rasterized images like I did before, but have a query out about that.
And weird artifacts are appearing in the image. Will have to see what I can
do. I know you aren't necessarily in a rush, but I don't want to delay.

**Comment by sean-fitzpatrick** [comment]
Really no rush at all on this.
What version of Asymptote are you using? (2.65 is best if it's installable on your system. 2.66 is needed for good svg output but that still needs to be built from source.)

Are you trying the HTML output?

**Comment by sean-fitzpatrick** [comment]
I am going to go out on a limb and say that it's unlikely we're ever going to move away from the current cone images, which are pretty OK, anyway. And a whole lot has happened with PreTeXt since this issue was opened. In particular, this issue predates the CLI! Now handling of external images is easy, so let's just keep them.
