### ISSUE TITLE
Some small global edits (a to-do list)

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#76]
There are a number of things that should be done with a global find-replace, but are probably better left until we have `master` even with `calc1-videos` (and the latter branch renamed as simply `videos` or something).
A number of these hit sections Alex is working on so I don't want to change until that work is done.

Here are a few I've noticed:

- `i.e.` should be replaced by `<ie/>`
- remove periods at the end of most captions (this one requires care since a few captions do require periods)
- using `<ndash/>` where we probably shouldn't (I see Alex is already doing this in Chapters 1 and 2)
- consistent use of spaces in `\text`
- units. (I've been working on this as I go but have probably missed a few)

**Comment by sean-fitzpatrick** [comment]
Should `\vec{T}` be `\overrightarrow{T}` for unit tangent vectors? [See here](http://www.cs.uleth.ca/~fitzpat/apex-calculus/sec_tan_norm.html#def_unit_tangent).

**Comment by Alex-Jordan** [comment]
Do you mean that it does not look good because the arrow is short? My first thoughts are to investigate some redefinition of `\vec`, or possibly making something semantic like `\unittangent`. Putting `\overrightarrow` into source feels non-semantic.

**Comment by sean-fitzpatrick** [comment]
Yes, the arrow seems too short to me. I'm open to defining a semantic macro.

Related: the derivative is typeset as `\vec{T}\,'(t)`. I think the thin space before the prime was needed in the APEX LaTeX, perhaps due to the choice of font. But it looks bad in MathJax.

**Comment by sean-fitzpatrick** [comment]
Turns out there's no change in output using `\overrightarrow{T}` anyway.
The arrow is short, but it's also too far to the right. But it seems a bit better if I do `\vec{{}T}`.
The empty brace pulls the arrow a bit to the left.
(First suggestion I found on Stack Exchange.)

**Comment by sean-fitzpatrick** [comment]
I'm going to define the following:
`\newcommand{\unittangent}{\vec{{}T}`
`\newcommand{\unittangentprime}{\vec{{}T}\hskip0.75pt}`
(the `hskip0.75pt` is the definition of `\primeskip`. It gives thinner space than `\,`)

I'll do similar for normal vectors.

**Comment by sean-fitzpatrick** [comment]
This is done, with the possible exception of units.
Correct usage of units is sort of case-by-case: is it in text, or math mode?
I've updated markup for units as I've worked through sections, and I've tried to be consistent:
`<quantity>` for units in text. In math, I've tried to use `123\,\text{units}`.

But most of my attention has been on later chapters. So earlier chapters might still need work.

Not sure this one is easy to do systematically. More likely we tackle them as we notice that it could be done better.
I'm closing the issue, but feel free to reopen if anyone wants to tackle units.
